/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ActivityAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ActivityCdn": {
      "type": "sst.aws.Router"
      "url": string
    }
    "DuffelApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EventbriteApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FoursquareApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FoursquareClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FoursquareClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GeonamesUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GraphhopperApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InteractionBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "OpenExchangeRatesAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenTableAffiliateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenchargeApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Pexels": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PredicthqApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RecommendationApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "RecommendationCache": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SerpApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseAnonKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabasePublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TicketmasterApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TimezonedbApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TravylEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "TravylWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "TripadvisorApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserInteractions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "VisualCrossingApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}