/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ActivityAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "InteractionBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "Pexels": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RecommendationApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "RecommendationCache": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SerpApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TravylEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "UserInteractions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}