// Explore activities data — browseable activities for a destination

export interface ExploreActivity {
  id: string;
  title: string;
  type: 'sightseeing' | 'restaurant' | 'activity';
  location: string;
  image: string;
  rating: number;
  price: string;
  duration: string;
  description: string;
  highlights: string[];
}

export const EXPLORE_ACTIVITIES: ExploreActivity[] = [
  {
    id: 'exp1',
    title: 'Colosseum Tour',
    type: 'sightseeing',
    location: 'Piazza del Colosseo, Rome',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.8,
    price: '€16-25',
    duration: '2.5h',
    description: 'Explore the iconic amphitheater where gladiators once battled.',
    highlights: ['Ancient architecture', 'Guided tour', 'Underground access'],
  },
  {
    id: 'exp2',
    title: 'Vatican Museums & Sistine Chapel',
    type: 'sightseeing',
    location: 'Vatican City',
    image: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.9,
    price: '€17-32',
    duration: '3h',
    description: 'Visit the world-famous Sistine Chapel and Vatican Museums.',
    highlights: ["Michelangelo's ceiling", 'Papal history', 'Renaissance art'],
  },
  {
    id: 'exp3',
    title: 'Traditional Roman Breakfast',
    type: 'restaurant',
    location: 'Trastevere, Rome',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.7,
    price: '€8-15',
    duration: '1h',
    description: 'Start your day with cornetto and cappuccino at a local café.',
    highlights: ['Fresh pastries', 'Authentic café', 'Local atmosphere'],
  },
  {
    id: 'exp4',
    title: 'Trattoria Dinner',
    type: 'restaurant',
    location: 'Centro Storico, Rome',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.8,
    price: '€25-45',
    duration: '2h',
    description: 'Enjoy authentic Roman cuisine including cacio e pepe.',
    highlights: ['Traditional recipes', 'House wine', 'Cozy ambiance'],
  },
  {
    id: 'exp5',
    title: 'Trevi Fountain & Spanish Steps',
    type: 'sightseeing',
    location: 'Centro, Rome',
    image: 'https://images.unsplash.com/photo-1525874684015-58379d421a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.7,
    price: 'Free',
    duration: '2h',
    description: "Visit Rome's most famous fountain. Don't forget to throw a coin!",
    highlights: ['Baroque fountain', 'Photo opportunities', 'Shopping nearby'],
  },
  {
    id: 'exp6',
    title: 'Pasta Making Class',
    type: 'activity',
    location: 'Monti, Rome',
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.9,
    price: '€65-85',
    duration: '3h',
    description: 'Learn to make fresh pasta from scratch with a local chef.',
    highlights: ['Hands-on cooking', 'Professional chef', 'Wine pairing'],
  },
  {
    id: 'exp7',
    title: 'Roman Forum',
    type: 'sightseeing',
    location: 'Via della Salara Vecchia, Rome',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.6,
    price: '€16',
    duration: '2h',
    description: 'Walk through the heart of ancient Rome.',
    highlights: ['Ancient ruins', 'Historical site', 'Palatine Hill included'],
  },
  {
    id: 'exp8',
    title: 'Gelato Tasting Tour',
    type: 'activity',
    location: 'Various locations, Rome',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.8,
    price: '€35-50',
    duration: '2h',
    description: 'Sample the best gelato in Rome.',
    highlights: ['Multiple gelaterias', 'Flavor varieties', 'Walking tour'],
  },
  {
    id: 'exp9',
    title: 'Villa Borghese Gardens',
    type: 'activity',
    location: 'Villa Borghese, Rome',
    image: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.7,
    price: 'Free',
    duration: '2h',
    description: "Relax in Rome's most famous park.",
    highlights: ['Peaceful gardens', 'Borghese Gallery', 'Panoramic views'],
  },
  {
    id: 'exp10',
    title: 'Pantheon',
    type: 'sightseeing',
    location: 'Piazza della Rotonda, Rome',
    image: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.9,
    price: 'Free',
    duration: '1h',
    description: 'Marvel at the best-preserved ancient Roman building.',
    highlights: ['Ancient architecture', 'Oculus dome', 'Free entry'],
  },
  {
    id: 'exp11',
    title: 'Catacombs Tour',
    type: 'sightseeing',
    location: 'Via Appia Antica, Rome',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.6,
    price: '€10-15',
    duration: '2h',
    description: 'Explore the underground burial chambers.',
    highlights: ['Underground tunnels', 'Historical significance', 'Guided tour'],
  },
  {
    id: 'exp12',
    title: 'Pizza Making Workshop',
    type: 'activity',
    location: 'Testaccio, Rome',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    rating: 4.8,
    price: '€55-75',
    duration: '2.5h',
    description: 'Learn authentic Roman-style pizza making.',
    highlights: ['Thin crust technique', 'Wood-fired oven', 'Eat your creation'],
  },
];
