import type { PlaceItem } from '../types';

export const MOCK_PLACES: PlaceItem[] = [
  // ── Destinations (~20) ────────────────────────────────────
  {
    id: 'p1',
    name: 'Blue Lagoon',
    image: 'https://images.unsplash.com/photo-1515861461802-2bfba48dce31?w=800',
    images: [
      'https://images.unsplash.com/photo-1515861461802-2bfba48dce31?w=800',
      'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800',
      'https://images.unsplash.com/photo-1476610182048-b716b8515aaa?w=800',
    ],
    type: 'destination',
    rating: 4.9,
    tagline: 'Grindavík, Iceland',
    category: 'Wellness',
    description: 'Geothermal spa surrounded by lava fields with milky-blue water.',
    tags: ['Spa', 'Hot Springs', 'Iconic'],
    latitude: 63.8804,
    longitude: -22.4495,
    priceLevel: 3,
    hours: 'Daily 8:00 AM – 9:00 PM (seasonal)',
    phone: '+354 420 8800',
    website: 'https://www.bluelagoon.com',
    reviewCount: 28400,
    address: 'Norðurljósavegur 9, 240 Grindavík, Iceland',
    bestTimeToVisit: 'September–March for Northern Lights combo visits',
    duration: '2-3 days',
    admissionFee: 'Free (spa entry from €75)',
    tips: [
      'Book the Comfort package at minimum — the in-water drink is worth it',
      'Apply the free silica mud mask and leave it on for 10 minutes',
      'Visit late afternoon to catch sunset over the steam',
    ],
    accessibility: ['Wheelchair accessible entrance and changing rooms', 'Pool lift available on request'],
    nearbyPlaces: ['p13', 'e4', 'e8'],
  },
  {
    id: 'p2',
    name: 'Marrakech Medina',
    image: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800',
    type: 'destination',
    rating: 4.7,
    tagline: 'Marrakech, Morocco',
    category: 'Cultural',
    description: 'Labyrinthine souks, riads, and vibrant Jemaa el-Fnaa square.',
    tags: ['Markets', 'Culture', 'Architecture'],
    latitude: 31.6295,
    longitude: -7.9811,
    priceLevel: 2,
    hours: 'Souks: 9:00 AM – 8:00 PM, Jemaa el-Fnaa: all day',
    phone: '+212 524 438 532',
    website: 'https://www.visitmarrakech.com',
    reviewCount: 19200,
    address: 'Medina Quarter, Marrakech 40000, Morocco',
    bestTimeToVisit: 'March–May or September–November for mild weather',
    duration: '2-3 days',
    admissionFee: 'Free',
    tips: [
      'Negotiate prices to about 40% of the initial ask in the souks',
      'Hire a local guide for the first visit — the medina is genuinely easy to get lost in',
      'Try the orange juice stalls on the square edge, not the center ones',
    ],
    accessibility: ['Uneven cobblestone streets throughout', 'Limited wheelchair access in the souks'],
    nearbyPlaces: ['e7', 'p18', 'a1'],
  },
  {
    id: 'p3',
    name: 'Ubud Rice Terraces',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    type: 'destination',
    rating: 4.8,
    tagline: 'Bali, Indonesia',
    category: 'Nature',
    description: 'Emerald rice paddies carved into volcanic hillsides.',
    tags: ['Nature', 'Hiking', 'Photography'],
    latitude: -8.4095,
    longitude: 115.3126,
    priceLevel: 2,
    hours: 'Daily 6:00 AM – 6:00 PM',
    phone: '+62 361 975 051',
    website: 'https://www.tegallalang.com',
    reviewCount: 14800,
    address: 'Tegallalang, Ubud, Gianyar Regency, Bali 80571, Indonesia',
    bestTimeToVisit: 'April–October (dry season), early morning for fewest crowds',
    duration: '2-3 days',
    admissionFee: 'Free (donation IDR 20,000 appreciated)',
    tips: [
      'Arrive before 8 AM to photograph the terraces without crowds',
      'Wear sturdy sandals — the paths are narrow and can be slippery',
      'The swing photo ops charge separately; negotiate before getting on',
    ],
    accessibility: ['Steep uneven terrain with narrow paths', 'Not suitable for wheelchairs or mobility devices'],
    nearbyPlaces: ['a7', 'e5', 'p9'],
  },
  {
    id: 'p4',
    name: 'Cappadocia Balloons',
    image: 'https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?w=800',
    images: [
      'https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?w=800',
      'https://images.unsplash.com/photo-1570939274717-7eda259b50ed?w=800',
      'https://images.unsplash.com/photo-1526048598645-62b31f82b8f5?w=800',
    ],
    type: 'destination',
    rating: 4.9,
    tagline: 'Göreme, Turkey',
    category: 'Adventure',
    description: 'Hundreds of hot air balloons at sunrise over fairy chimneys.',
    tags: ['Balloons', 'Sunrise', 'Unique'],
    latitude: 38.6431,
    longitude: 34.8289,
    priceLevel: 3,
    hours: 'Balloon flights launch at sunrise (approx. 5:00–6:30 AM)',
    phone: '+90 384 271 2442',
    website: 'https://www.goreme.com',
    reviewCount: 22100,
    address: 'Göreme, Nevşehir 50180, Turkey',
    bestTimeToVisit: 'April–June and September–November for clearest skies',
    duration: '2-3 days',
    admissionFee: 'Free (balloon rides from €150)',
    tips: [
      'Book your balloon ride months in advance — they sell out and flights cancel for wind',
      'Stay in a cave hotel; the experience is half the reason to visit',
      'Rent an ATV to explore the valleys beyond the tourist spots',
    ],
    accessibility: ['Balloon basket entry requires stepping over 1m wall', 'Cave hotels have limited lift access'],
    nearbyPlaces: ['p5', 'a1', 'p12'],
  },
  {
    id: 'p5',
    name: 'Santorini Sunset',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
    type: 'destination',
    rating: 4.8,
    tagline: 'Oia, Greece',
    category: 'Romantic',
    description: 'White-washed cliffs with blue domes overlooking the caldera.',
    tags: ['Sunset', 'Romance', 'Views'],
    latitude: 36.4618,
    longitude: 25.3753,
    priceLevel: 3,
    hours: 'Open year-round; sunset ~6:30 PM summer, ~5:00 PM winter',
    phone: '+30 22860 71234',
    website: 'https://www.santorini.gr',
    reviewCount: 31500,
    address: 'Oia, Santorini 847 02, Greece',
    bestTimeToVisit: 'June–September for warmest weather and best sunsets',
    duration: '2-3 days',
    admissionFee: 'Free',
    tips: [
      'Claim your sunset spot at the castle ruins an hour early in peak season',
      'Stay in Imerovigli for caldera views at half the Oia price',
      'Take the hike from Fira to Oia (3 hours) for the best island views',
    ],
    accessibility: ['Many steep stairs with no railings', 'Donkey taxis available from port but controversial'],
    nearbyPlaces: ['p6', 'p12', 'p4'],
  },
  {
    id: 'p6',
    name: 'Amalfi Coast',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800',
    type: 'destination',
    rating: 4.7,
    tagline: 'Amalfi, Italy',
    category: 'Coastal',
    description: 'Pastel villages perched on dramatic Mediterranean cliffs.',
    tags: ['Coast', 'Italy', 'Scenic Drive'],
    latitude: 40.6340,
    longitude: 14.6027,
    priceLevel: 3,
    hours: 'Open year-round; best explored April–October',
    phone: '+39 089 871 107',
    website: 'https://www.amalficoast.com',
    reviewCount: 26300,
    address: 'Amalfi, SA 84011, Italy',
    bestTimeToVisit: 'May or September for warm weather without July/August crowds',
    duration: '3-4 days',
    admissionFee: 'Free',
    tips: [
      'Take the SITA bus instead of driving — the roads are terrifyingly narrow',
      'Visit Ravello for peaceful gardens and far fewer tourists',
      'Buy limoncello directly from family producers, not souvenir shops',
    ],
    accessibility: ['Most towns involve steep stairs and hills', 'Accessible beaches limited to Maiori and Minori'],
    nearbyPlaces: ['p19', 'a3', 'r2'],
  },
  {
    id: 'p7',
    name: 'Kyoto Bamboo Grove',
    image: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800',
    images: [
      'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
    ],
    type: 'destination',
    rating: 4.8,
    tagline: 'Kyoto, Japan',
    category: 'Nature',
    description: 'Towering bamboo stalks creating an otherworldly canopy.',
    tags: ['Nature', 'Zen', 'Photography'],
    latitude: 35.0170,
    longitude: 135.6713,
    priceLevel: 2,
    hours: 'Open 24 hours (best visited during daylight)',
    phone: '+81 75 861 0012',
    website: 'https://www.japan-guide.com/e/e3912.html',
    reviewCount: 18900,
    address: 'Sagatenryuji Susukinobabacho, Ukyo Ward, Kyoto 616-8394, Japan',
    bestTimeToVisit: 'Early morning (before 8 AM) or late November for autumn colors',
    duration: '2-3 days',
    admissionFee: 'Free',
    tips: [
      'Arrive at sunrise — by 9 AM the path is shoulder-to-shoulder tourists',
      'Combine with Tenryu-ji Temple right next door',
      'Rent a kimono in Arashiyama for photos; shops open at 9 AM',
    ],
    accessibility: ['Paved flat path through the grove', 'Wheelchair accessible'],
    nearbyPlaces: ['p20', 'e11', 'r1'],
  },
  {
    id: 'p8',
    name: 'Banff National Park',
    image: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800',
    type: 'destination',
    rating: 4.9,
    tagline: 'Alberta, Canada',
    category: 'Adventure',
    description: 'Turquoise lakes and Rocky Mountain peaks.',
    tags: ['Mountains', 'Hiking', 'Lakes'],
    latitude: 51.4968,
    longitude: -115.9281,
    priceLevel: 2,
    hours: 'Park open 24 hours; visitor center 9:00 AM – 5:00 PM',
    phone: '+1 403 762 1550',
    website: 'https://www.pc.gc.ca/en/pn-np/ab/banff',
    reviewCount: 34200,
    address: 'Banff National Park, AB T1L 1K2, Canada',
    bestTimeToVisit: 'June–September for hiking; January–March for skiing',
    duration: '3-5 days',
    admissionFee: 'Free (park pass CAD $11/day)',
    tips: [
      'Get to Lake Louise by 6 AM in summer or you will not find parking',
      'Moraine Lake is even more stunning than Louise — do not skip it',
      'Bear spray is essential on trails; rent it in town if you did not bring any',
    ],
    accessibility: ['Many paved lakeside paths', 'Accessible viewpoints at Lake Louise and Bow Falls'],
    nearbyPlaces: ['e12', 'p16', 'p11'],
  },
  {
    id: 'p9',
    name: 'Maldives Overwater',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    images: [
      'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
      'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800',
      'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800',
    ],
    type: 'destination',
    rating: 4.9,
    tagline: 'Maldives',
    category: 'Luxury',
    description: 'Crystal clear waters and overwater bungalows.',
    tags: ['Beach', 'Luxury', 'Snorkeling'],
    latitude: 3.2028,
    longitude: 73.2207,
    priceLevel: 4,
    hours: 'Resorts operate year-round',
    phone: '+960 664 4100',
    website: 'https://www.visitmaldives.com',
    reviewCount: 21700,
    address: 'North Malé Atoll, Maldives',
    bestTimeToVisit: 'November–April (dry season with calm seas)',
    duration: '4-7 days',
    admissionFee: 'Free',
    tips: [
      'Choose a resort on the house reef for the best snorkeling from your room',
      'Book a seaplane transfer — the aerial views are part of the experience',
      'Bring reef-safe sunscreen; it is strictly enforced and expensive on-island',
    ],
    accessibility: ['Overwater villas require stepping over thresholds', 'Some resorts offer beach-level accessible rooms'],
    nearbyPlaces: ['p14', 'p3', 'e2'],
  },
  {
    id: 'p10',
    name: 'Havana Vieja',
    image: 'https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=800',
    type: 'destination',
    rating: 4.5,
    tagline: 'Havana, Cuba',
    category: 'Cultural',
    description: 'Vintage cars, colonial architecture, and salsa rhythms.',
    tags: ['Culture', 'History', 'Music'],
    latitude: 23.1356,
    longitude: -82.3590,
    priceLevel: 2,
    hours: 'Outdoor areas open 24 hours; museums 9:00 AM – 5:00 PM',
    phone: '+53 7 866 3109',
    website: 'https://www.cubatravel.cu',
    reviewCount: 11800,
    address: 'Habana Vieja, Havana, Cuba',
    bestTimeToVisit: 'November–April to avoid hurricane season and extreme heat',
    duration: '2-3 days',
    admissionFee: 'Free',
    tips: [
      'Bring cash in EUR or CAD — USD gets a 10% penalty on exchange',
      'Classic car tours are great but negotiate a fixed price upfront',
      'Try the mojitos at La Bodeguita del Medio, daiquiris at El Floridita',
    ],
    accessibility: ['Uneven sidewalks and cobblestone streets', 'Few buildings have elevator access'],
    nearbyPlaces: ['r9', 'ev4', 'a8'],
  },
  {
    id: 'p11',
    name: 'Swiss Alps Train',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800',
    type: 'destination',
    rating: 4.8,
    tagline: 'Zermatt, Switzerland',
    category: 'Adventure',
    description: 'Scenic railway winding through alpine meadows to the Matterhorn.',
    tags: ['Mountains', 'Train', 'Snow'],
    latitude: 46.0207,
    longitude: 7.7491,
    priceLevel: 3,
    hours: 'Glacier Express: daily departures at 8:52 AM and 9:52 AM',
    phone: '+41 27 927 7777',
    website: 'https://www.glacierexpress.ch',
    reviewCount: 16700,
    address: 'Bahnhofplatz 7, 3920 Zermatt, Switzerland',
    bestTimeToVisit: 'June–September for clear mountain views; December–March for skiing',
    duration: '2-3 days',
    admissionFee: 'Free (Glacier Express from CHF 152)',
    tips: [
      'Book a seat on the right side heading to Zermatt for the best Matterhorn views',
      'The Swiss Travel Pass gives 50% off Glacier Express; buy it before you arrive',
      'Zermatt is car-free — enjoy the quiet, but pack light for the walk to your hotel',
    ],
    accessibility: ['Glacier Express has wheelchair-accessible carriages with advance notice', 'Zermatt has electric taxis'],
    nearbyPlaces: ['e6', 'a12', 'p8'],
  },
  {
    id: 'p12',
    name: 'Dubrovnik Old Town',
    image: 'https://images.unsplash.com/photo-1555990793-da11153b2473?w=800',
    type: 'destination',
    rating: 4.7,
    tagline: 'Dubrovnik, Croatia',
    category: 'Historical',
    description: 'Medieval walled city on the Adriatic, the "Pearl of the Adriatic".',
    tags: ['History', 'Coast', 'GOT'],
    latitude: 42.6507,
    longitude: 18.0944,
    priceLevel: 2,
    hours: 'City walls: 8:00 AM – 6:30 PM (summer), 9:00 AM – 3:00 PM (winter)',
    phone: '+385 20 323 887',
    website: 'https://www.tzdubrovnik.hr',
    reviewCount: 19800,
    address: 'Stari Grad, 20000 Dubrovnik, Croatia',
    bestTimeToVisit: 'May or October to avoid cruise ship crowds',
    duration: '2-3 days',
    admissionFee: 'Free (city walls €35)',
    tips: [
      'Walk the walls first thing in the morning before the cruise ships dock',
      'Take the cable car up Mount Srđ for sunset views over the old town',
      'Swim at Banje Beach right outside the walls — bring water shoes for the rocks',
    ],
    accessibility: ['Extensive stairs and polished stone streets', 'City walls are not wheelchair accessible'],
    nearbyPlaces: ['p5', 'p6', 'p15'],
  },
  {
    id: 'p13',
    name: 'Northern Lights',
    image: 'https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=800',
    type: 'destination',
    rating: 4.9,
    tagline: 'Tromsø, Norway',
    category: 'Nature',
    description: 'Aurora borealis dancing across the Arctic sky.',
    tags: ['Aurora', 'Winter', 'Arctic'],
    latitude: 69.6496,
    longitude: 18.9560,
    priceLevel: 3,
    hours: 'Aurora visible September–March, typically 6:00 PM – 2:00 AM',
    phone: '+47 77 61 00 00',
    website: 'https://www.visittromso.no',
    reviewCount: 15400,
    address: 'Tromsø 9008, Norway',
    bestTimeToVisit: 'Late September–late March with peak activity around equinoxes',
    duration: '2-3 days',
    admissionFee: 'Free',
    tips: [
      'Book a guided minibus chase tour — they follow clear skies and know the best spots',
      'Download the Aurora app for real-time KP index alerts',
      'Dress in layers with windproof outer shell; -15°C is normal while you wait',
    ],
    accessibility: ['Aurora viewpoints are often in open fields', 'Some tour operators offer accessible vehicles'],
    nearbyPlaces: ['p1', 'e4', 'e8'],
  },
  {
    id: 'p14',
    name: 'Bora Bora Lagoon',
    image: 'https://images.unsplash.com/photo-1589197331516-4d84b72ebde3?w=800',
    type: 'destination',
    rating: 4.8,
    tagline: 'French Polynesia',
    category: 'Luxury',
    description: 'Volcanic island surrounded by a turquoise lagoon and barrier reef.',
    tags: ['Island', 'Luxury', 'Diving'],
    latitude: -16.5004,
    longitude: -151.7415,
    priceLevel: 4,
    hours: 'Resorts and lagoon tours operate year-round',
    phone: '+689 40 607 600',
    website: 'https://www.tahiti-tourisme.com',
    reviewCount: 12300,
    address: 'Bora Bora 98730, French Polynesia',
    bestTimeToVisit: 'May–October (dry season)',
    duration: '4-5 days',
    admissionFee: 'Free',
    tips: [
      'Snorkel with manta rays and reef sharks on a lagoon tour — completely safe',
      'The InterContinental Thalasso has a glass-floor overwater villa worth the splurge',
      'Bring everything you need — island prices are double the mainland',
    ],
    accessibility: ['Boat transfers required between most locations', 'Some resorts offer accessible overwater units'],
    nearbyPlaces: ['p9', 'e2', 'p3'],
  },
  {
    id: 'p15',
    name: 'Prague Castle',
    image: 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800',
    type: 'destination',
    rating: 4.6,
    tagline: 'Prague, Czech Republic',
    category: 'Historical',
    description: 'Gothic spires and baroque palaces along the Vltava River.',
    tags: ['Castle', 'History', 'Architecture'],
    latitude: 50.0911,
    longitude: 14.4003,
    priceLevel: 2,
    hours: 'Castle grounds: 6:00 AM – 10:00 PM; interiors: 9:00 AM – 5:00 PM',
    phone: '+420 224 373 368',
    website: 'https://www.hrad.cz',
    reviewCount: 23600,
    address: 'Hradčany, 119 08 Prague 1, Czech Republic',
    bestTimeToVisit: 'April–May or September–October for mild weather and fewer crowds',
    duration: '2-3 days',
    admissionFee: 'Free (interior circuit tickets from CZK 250)',
    tips: [
      'Enter from the eastern gate to avoid the long security line at the main entrance',
      'Golden Lane is charming but tiny — visit at opening time or skip on busy days',
      'Walk across Charles Bridge at sunrise for the best photo ops',
    ],
    accessibility: ['Cobblestone paths throughout', 'Elevator access to St. Vitus Cathedral available'],
    nearbyPlaces: ['a12', 'p12', 'ev5'],
  },
  {
    id: 'p16',
    name: 'Patagonia Torres',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    type: 'destination',
    rating: 4.9,
    tagline: 'Torres del Paine, Chile',
    category: 'Adventure',
    description: 'Granite towers, glaciers, and pristine wilderness.',
    tags: ['Trekking', 'Wilderness', 'Mountains'],
    latitude: -50.9423,
    longitude: -73.4068,
    priceLevel: 2,
    hours: 'Park open daily; summer 7:00 AM – 9:00 PM, winter 8:00 AM – 6:00 PM',
    phone: '+56 61 269 1931',
    website: 'https://www.torresdelpaine.com',
    reviewCount: 11200,
    address: 'Torres del Paine National Park, Magallanes, Chile',
    bestTimeToVisit: 'November–March (Patagonian summer) for hikeable conditions',
    duration: '3-5 days',
    admissionFee: 'Free (park entry CLP 26,000)',
    tips: [
      'Book W Trek refugios at least 6 months ahead — they fill up fast',
      'Pack for four seasons in one day; Patagonian wind is no joke',
      'The Mirador Las Torres sunrise hike is brutal but life-changing',
    ],
    accessibility: ['Rugged backcountry trails only', 'Viewpoint at Lago Grey accessible by vehicle'],
    nearbyPlaces: ['a6', 'e3', 'p8'],
  },
  {
    id: 'p17',
    name: 'Lisbon Tram 28',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800',
    type: 'destination',
    rating: 4.5,
    tagline: 'Lisbon, Portugal',
    category: 'Cultural',
    description: 'Vintage yellow tram winding through historic neighborhoods.',
    tags: ['Tram', 'Culture', 'Pastéis'],
    latitude: 38.7139,
    longitude: -9.1394,
    priceLevel: 2,
    hours: 'Tram 28: daily 6:15 AM – 9:00 PM, every 10–15 minutes',
    phone: '+351 21 361 3000',
    website: 'https://www.visitlisboa.com',
    reviewCount: 17500,
    address: 'Lisbon, Portugal',
    bestTimeToVisit: 'March–May or September–October for pleasant temperatures',
    duration: '2-3 days',
    admissionFee: 'Free (tram ticket €3.00)',
    tips: [
      'Board at Martim Moniz to get a seat; pickpockets work the crowded stops',
      'Get a pastel de nata at Manteigaria, not the tourist-trap Pastéis de Belém line',
      'Time Out Market is overpriced but Cervejaria Ramiro is where locals eat seafood',
    ],
    accessibility: ['Vintage trams are not wheelchair accessible', 'Modern tram 15E to Belém is accessible'],
    nearbyPlaces: ['p6', 'a9', 'ev6'],
  },
  {
    id: 'p18',
    name: 'Serengeti Safari',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76b94d42?w=800',
    type: 'destination',
    rating: 4.9,
    tagline: 'Tanzania',
    category: 'Adventure',
    description: 'The greatest wildlife migration on Earth across endless plains.',
    tags: ['Safari', 'Wildlife', 'Migration'],
    latitude: -2.3333,
    longitude: 34.8333,
    priceLevel: 3,
    hours: 'Park gates: 6:00 AM – 6:00 PM daily',
    phone: '+255 27 250 8082',
    website: 'https://www.serengeti.com',
    reviewCount: 9800,
    address: 'Serengeti National Park, Tanzania',
    bestTimeToVisit: 'June–October for Great Migration river crossings',
    duration: '3-5 days',
    admissionFee: 'Free (park fee USD $70/day)',
    tips: [
      'A three-night stay is the minimum to see meaningful wildlife; five is ideal',
      'Central Serengeti (Seronera) is best year-round; northern Serengeti for migration crossings',
      'Bring a zoom lens of at least 200mm and binoculars for every passenger',
    ],
    accessibility: ['Game drives in modified 4x4 vehicles', 'Some lodges offer accessible rooms'],
    nearbyPlaces: ['e1', 'e10', 'p2'],
  },
  {
    id: 'p19',
    name: 'Cinque Terre',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800',
    type: 'destination',
    rating: 4.7,
    tagline: 'Liguria, Italy',
    category: 'Coastal',
    description: 'Five colorful fishing villages clinging to the Italian Riviera.',
    tags: ['Hiking', 'Coast', 'Village'],
    latitude: 44.1461,
    longitude: 9.6439,
    priceLevel: 2,
    hours: 'Villages open 24 hours; hiking trails close at sunset',
    phone: '+39 0187 762 600',
    website: 'https://www.parconazionale5terre.it',
    reviewCount: 20100,
    address: 'Cinque Terre, La Spezia, Liguria, Italy',
    bestTimeToVisit: 'Late April–May or September for warm weather, fewer tourists',
    duration: '2-3 days',
    admissionFee: 'Free (Cinque Terre Card from €7.50 for trails)',
    tips: [
      'Stay in Manarola or Corniglia for fewer crowds and better prices than Riomaggiore',
      'Take the train between villages and hike only the scenic sections',
      'Try the pesto trofie — Liguria invented pesto and it is noticeably better here',
    ],
    accessibility: ['Very steep terrain with hundreds of stairs', 'Train stations connect all five villages for limited-mobility visitors'],
    nearbyPlaces: ['p6', 'e9', 'r2'],
  },
  {
    id: 'p20',
    name: 'Tokyo Shibuya',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    type: 'destination',
    rating: 4.6,
    tagline: 'Tokyo, Japan',
    category: 'Urban',
    description: 'Neon-lit crossroads of tradition and futurism.',
    tags: ['City', 'Food', 'Nightlife'],
    latitude: 35.6595,
    longitude: 139.7004,
    priceLevel: 2,
    hours: 'Shibuya Crossing active 24 hours; shops 10:00 AM – 9:00 PM',
    phone: '+81 3 3463 3460',
    website: 'https://www.gotokyo.org',
    reviewCount: 27800,
    address: 'Shibuya, Tokyo 150-0002, Japan',
    bestTimeToVisit: 'March–May (cherry blossoms) or October–November (autumn color)',
    duration: '3-5 days',
    admissionFee: 'Free',
    tips: [
      'Watch the crossing from the Starbucks above or Shibuya Sky observation deck',
      'Get a Suica card immediately — it works on all trains and most vending machines',
      'Explore the side streets of Nonbei Yokocho for tiny atmospheric bars',
    ],
    accessibility: ['Shibuya station has elevators on all lines', 'Crossing has audio signals for visually impaired'],
    nearbyPlaces: ['r1', 'r4', 'ev7'],
  },

  // ── Attractions (~12) ─────────────────────────────────────
  {
    id: 'a1',
    name: 'Petra Treasury',
    image: 'https://images.unsplash.com/photo-1579606032821-4e6161c81571?w=800',
    type: 'attraction',
    rating: 4.9,
    tagline: 'Wadi Musa, Jordan',
    category: 'Ancient',
    description: 'Rose-red city carved into sandstone cliffs 2,000 years ago.',
    tags: ['Ancient', 'Wonder', 'Archaeology'],
    latitude: 30.3285,
    longitude: 35.4444,
    priceLevel: 2,
    hours: 'Daily 6:00 AM – 6:00 PM (summer), 6:00 AM – 4:00 PM (winter)',
    phone: '+962 3 215 6044',
    website: 'https://www.visitpetra.jo',
    reviewCount: 24100,
    address: 'Wadi Musa, Ma\'an Governorate, Jordan',
    bestTimeToVisit: 'March–May or October–November when it is not scorching',
    duration: '1-2 days',
    admissionFee: 'JOD 50 (one day), JOD 55 (two days)',
    tips: [
      'Arrive at 6 AM to walk the Siq in solitude and see the Treasury before the crowds',
      'Petra by Night (Monday, Wednesday, Thursday) is magical but crowded — manage expectations',
      'Hike up to the Monastery — it is less famous but more impressive than the Treasury',
    ],
    accessibility: ['Siq pathway is sandy and uneven', 'Horse carriage available for part of the Siq'],
    nearbyPlaces: ['p4', 'p2', 'a4'],
  },
  {
    id: 'a2',
    name: 'Eiffel Tower',
    image: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=800',
    images: [
      'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=800',
      'https://images.unsplash.com/photo-1511739001486-6bfe10ce65f6?w=800',
      'https://images.unsplash.com/photo-1431274172761-fca41d930114?w=800',
    ],
    type: 'attraction',
    rating: 4.8,
    tagline: 'Paris, France',
    category: 'Landmark',
    description: 'Iron lattice tower and global icon of Paris.',
    tags: ['Landmark', 'Views', 'Iconic'],
    latitude: 48.8584,
    longitude: 2.2945,
    priceLevel: 2,
    hours: 'Daily 9:30 AM – 11:45 PM (summer), 9:30 AM – 10:45 PM (winter)',
    phone: '+33 8 92 70 12 39',
    website: 'https://www.toureiffel.paris',
    reviewCount: 41200,
    address: 'Champ de Mars, 5 Av. Anatole France, 75007 Paris, France',
    bestTimeToVisit: 'Sunset for golden hour views; skip July–August peak crowds',
    duration: '2-3 hours',
    admissionFee: '€17.10 (stairs to 2nd floor), €26.80 (lift to summit)',
    tips: [
      'Book summit tickets online 60 days ahead — they sell out fast',
      'Take the stairs to the 2nd floor for a workout and zero queue',
      'The sparkle show runs every hour on the hour after dark for 5 minutes',
    ],
    accessibility: ['Elevator access to 1st and 2nd floors', 'Wheelchair accessible restrooms on each level'],
    nearbyPlaces: ['r5', 'ev3', 'a3'],
  },
  {
    id: 'a3',
    name: 'Colosseum',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
    type: 'attraction',
    rating: 4.8,
    tagline: 'Rome, Italy',
    category: 'Ancient',
    description: 'Iconic amphitheater where gladiators once fought.',
    tags: ['History', 'Architecture', 'Ancient'],
    latitude: 41.8902,
    longitude: 12.4922,
    priceLevel: 2,
    hours: 'Daily 9:00 AM – 7:00 PM (last entry 6:15 PM)',
    phone: '+39 06 3996 7700',
    website: 'https://www.colosseo.it',
    reviewCount: 38700,
    address: 'Piazza del Colosseo, 1, 00184 Roma RM, Italy',
    bestTimeToVisit: 'Early morning or late afternoon to avoid midday heat and crowds',
    duration: '1-2 hours',
    admissionFee: '€16 (includes Roman Forum and Palatine Hill)',
    tips: [
      'Buy the combo ticket from Palatine Hill entrance — there is no line',
      'The underground and arena floor tour is worth the extra cost',
      'Skip the gladiator photo guys outside — it is a known scam',
    ],
    accessibility: ['Elevator access to upper levels', 'Accessible entrance on the south side'],
    nearbyPlaces: ['p6', 'r2', 'e9'],
  },
  {
    id: 'a4',
    name: 'Taj Mahal',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800',
    type: 'attraction',
    rating: 4.9,
    tagline: 'Agra, India',
    category: 'Historical',
    description: 'Ivory marble mausoleum, a monument to eternal love.',
    tags: ['Monument', 'Marble', 'Wonder'],
    latitude: 27.1751,
    longitude: 78.0421,
    priceLevel: 2,
    hours: 'Daily sunrise–sunset; closed Fridays',
    phone: '+91 562 222 6431',
    website: 'https://www.tajmahal.gov.in',
    reviewCount: 33500,
    address: 'Dharmapuri, Forest Colony, Tajganj, Agra, UP 282001, India',
    bestTimeToVisit: 'October–March for cooler temperatures; sunrise for the best light',
    duration: '2-3 hours',
    admissionFee: '₹1,100 (foreign visitors), ₹50 (Indian citizens)',
    tips: [
      'Enter from the east or west gate to avoid the main gate crowds',
      'Sunrise is magical but the light on the marble at sunset is equally stunning',
      'Leave electronics larger than a phone in the locker — they are strict',
    ],
    accessibility: ['Wheelchair available at the entrance free of charge', 'Mostly flat paved pathways'],
    nearbyPlaces: ['a5', 'a1', 'p2'],
  },
  {
    id: 'a5',
    name: 'Great Wall of China',
    image: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800',
    type: 'attraction',
    rating: 4.7,
    tagline: 'Beijing, China',
    category: 'Historical',
    description: 'Ancient fortification stretching across mountains and valleys.',
    tags: ['History', 'Hiking', 'Wonder'],
    latitude: 40.4319,
    longitude: 116.5704,
    priceLevel: 2,
    hours: 'Mutianyu section: 7:30 AM – 5:30 PM (summer), 8:00 AM – 5:00 PM (winter)',
    phone: '+86 10 6162 6505',
    website: 'https://www.mutianyugreatwall.com',
    reviewCount: 29800,
    address: 'Mutianyu, Huairou District, Beijing, China',
    bestTimeToVisit: 'April–May or September–November for best weather and visibility',
    duration: '2-3 hours',
    admissionFee: '¥40 (Mutianyu section)',
    tips: [
      'Choose Mutianyu over Badaling — fewer crowds and better views',
      'Take the toboggan ride down; it is a delightful way to return',
      'Bring snacks and water — options on the wall are overpriced and limited',
    ],
    accessibility: ['Cable car to upper sections available', 'Many steep and uneven stairs along the wall'],
    nearbyPlaces: ['a4', 'p7', 'a7'],
  },
  {
    id: 'a6',
    name: 'Machu Picchu',
    image: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800',
    images: [
      'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800',
      'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800',
      'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=800',
    ],
    type: 'attraction',
    rating: 4.9,
    tagline: 'Cusco, Peru',
    category: 'Ancient',
    description: 'Incan citadel perched high in the Andes mountains.',
    tags: ['Inca', 'Mountains', 'Wonder'],
    latitude: -13.1631,
    longitude: -72.5450,
    priceLevel: 2,
    hours: 'Daily 6:00 AM – 5:30 PM (timed entry slots)',
    phone: '+51 84 211 196',
    website: 'https://www.machupicchu.gob.pe',
    reviewCount: 27400,
    address: 'Machu Picchu, Aguas Calientes, Cusco 08680, Peru',
    bestTimeToVisit: 'May–September (dry season) for clear skies',
    duration: '2-3 hours',
    admissionFee: 'S/. 152 (~USD $40) per person',
    tips: [
      'Acclimatize in Cusco for 2 days before coming — altitude sickness is real at 2,430m',
      'The first bus up (5:30 AM) rewards you with misty, uncrowded ruins',
      'Huayna Picchu permits sell out months ahead and are worth every penny',
    ],
    accessibility: ['Rough stone paths and steep terraces throughout', 'No wheelchair access; requires moderate fitness'],
    nearbyPlaces: ['e3', 'p16', 'r9'],
  },
  {
    id: 'a7',
    name: 'Angkor Wat',
    image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800',
    type: 'attraction',
    rating: 4.8,
    tagline: 'Siem Reap, Cambodia',
    category: 'Ancient',
    description: 'The largest religious monument in the world at sunrise.',
    tags: ['Temple', 'Sunrise', 'Ancient'],
    latitude: 13.4125,
    longitude: 103.8670,
    priceLevel: 2,
    hours: 'Daily 5:00 AM – 5:30 PM',
    phone: '+855 63 765 577',
    website: 'https://www.angkorwat.org',
    reviewCount: 22900,
    address: 'Krong Siem Reap, Cambodia',
    bestTimeToVisit: 'November–February for cool, dry weather; sunrise is essential',
    duration: '2-3 hours',
    admissionFee: 'USD $37 (one day), $62 (three days)',
    tips: [
      'Buy the three-day pass — one day is not enough for the complex',
      'For sunrise, position yourself at the left (north) reflecting pool for the classic shot',
      'Hire a tuk-tuk driver for the day (USD $15–20) rather than joining a group tour',
    ],
    accessibility: ['Some temples have steep stairs with no railing', 'Main Angkor Wat temple has a wooden ramp on one side'],
    nearbyPlaces: ['p3', 'a5', 'e5'],
  },
  {
    id: 'a8',
    name: 'Christ the Redeemer',
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800',
    type: 'attraction',
    rating: 4.7,
    tagline: 'Rio de Janeiro, Brazil',
    category: 'Landmark',
    description: 'Art Deco statue overlooking Rio from Corcovado mountain.',
    tags: ['Statue', 'Views', 'Iconic'],
    latitude: -22.9519,
    longitude: -43.2105,
    priceLevel: 2,
    hours: 'Daily 8:00 AM – 7:00 PM',
    phone: '+55 21 2558 1329',
    website: 'https://www.cristoredentor.com.br',
    reviewCount: 31200,
    address: 'Parque Nacional da Tijuca, Alto da Boa Vista, Rio de Janeiro, RJ 20531-590, Brazil',
    bestTimeToVisit: 'Early morning for fewest clouds and crowds',
    duration: '1-2 hours',
    admissionFee: 'BRL 90 (high season), BRL 60 (low season), includes train',
    tips: [
      'Take the first train up at 8 AM — mornings are clearest',
      'Check the webcam before going; cloud cover can ruin the visit entirely',
      'The van from Paineiras is faster but the cog train ride is part of the experience',
    ],
    accessibility: ['Elevator and escalator access to the statue platform', 'Wheelchair accessible viewing area'],
    nearbyPlaces: ['ev4', 'p10', 'e10'],
  },
  {
    id: 'a9',
    name: 'Sagrada Família',
    image: 'https://images.unsplash.com/photo-1583779457711-ab081de64105?w=800',
    type: 'attraction',
    rating: 4.8,
    tagline: 'Barcelona, Spain',
    category: 'Architecture',
    description: "Gaudí's unfinished masterpiece with kaleidoscopic interiors.",
    tags: ['Gaudí', 'Church', 'Art'],
    latitude: 41.4036,
    longitude: 2.1744,
    priceLevel: 2,
    hours: 'Mon–Sat 9:00 AM – 8:00 PM, Sun 10:30 AM – 8:00 PM',
    phone: '+34 932 080 414',
    website: 'https://www.sagradafamilia.org',
    reviewCount: 35600,
    address: 'C/ de Mallorca, 401, 08013 Barcelona, Spain',
    bestTimeToVisit: 'Late afternoon when sunlight hits the stained glass on the western façade',
    duration: '1-2 hours',
    admissionFee: '€26 (basic), €36 (with tower access)',
    tips: [
      'Book the Nativity tower — the views and elevator ride are better than the Passion side',
      'Visit between 4–6 PM when the western sun creates a rainbow inside',
      'Audio guide is essential; without context you miss 90% of the symbolism',
    ],
    accessibility: ['Ground floor is wheelchair accessible', 'Towers not accessible for wheelchairs or mobility issues'],
    nearbyPlaces: ['r3', 'r7', 'ev6'],
  },
  {
    id: 'a10',
    name: 'Chichén Itzá',
    image: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800',
    type: 'attraction',
    rating: 4.7,
    tagline: 'Yucatán, Mexico',
    category: 'Ancient',
    description: 'Maya pyramid with perfect equinox shadow phenomenon.',
    tags: ['Maya', 'Pyramid', 'History'],
    latitude: 20.6843,
    longitude: -88.5678,
    priceLevel: 2,
    hours: 'Daily 8:00 AM – 5:00 PM (last entry 4:00 PM)',
    phone: '+52 985 851 0137',
    website: 'https://www.inah.gob.mx',
    reviewCount: 19500,
    address: 'Yucatán 97751, Mexico',
    bestTimeToVisit: 'Open at 8 AM or visit during equinox (March 20–21, Sept 22–23) for the serpent shadow',
    duration: '2-3 hours',
    admissionFee: 'MXN 571 (foreigners), MXN 80 (Mexican nationals)',
    tips: [
      'Arrive the moment gates open at 8 AM — by 10 AM tour buses flood the site',
      'Hire a guide at the entrance (MXN 800–1000) for the full historical story',
      'Clap in front of the pyramid to hear the quetzal bird echo — a deliberate acoustic design',
    ],
    accessibility: ['Flat gravel paths between main structures', 'Cannot climb the pyramid'],
    nearbyPlaces: ['ev1', 'a6', 'r9'],
  },
  {
    id: 'a11',
    name: 'Sydney Opera House',
    image: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800',
    type: 'attraction',
    rating: 4.6,
    tagline: 'Sydney, Australia',
    category: 'Architecture',
    description: 'Sail-shaped performing arts center on the harbor.',
    tags: ['Architecture', 'Performing Arts'],
    latitude: -33.8568,
    longitude: 151.2153,
    priceLevel: 2,
    hours: 'Tours: daily 9:00 AM – 5:00 PM; performances vary',
    phone: '+61 2 9250 7111',
    website: 'https://www.sydneyoperahouse.com',
    reviewCount: 25300,
    address: 'Bennelong Point, Sydney NSW 2000, Australia',
    bestTimeToVisit: 'Sunset for the best exterior photos; book an evening performance',
    duration: '1-2 hours',
    admissionFee: 'AUD $43 (guided tour), performance tickets vary',
    tips: [
      'Book a backstage tour for behind-the-scenes access and incredible acoustics demos',
      'Walk around to Mrs Macquaries Point for the iconic Opera House + Harbour Bridge shot',
      'Catch a show — even a cheap seat in the Concert Hall is a lifetime experience',
    ],
    accessibility: ['Fully wheelchair accessible with ramps and elevators', 'Assisted listening devices available for performances'],
    nearbyPlaces: ['e2', 'p14', 'r8'],
  },
  {
    id: 'a12',
    name: 'Neuschwanstein Castle',
    image: 'https://images.unsplash.com/photo-1534313314376-a72289b6181e?w=800',
    type: 'attraction',
    rating: 4.7,
    tagline: 'Bavaria, Germany',
    category: 'Historical',
    description: 'Fairytale castle that inspired Disney on a Bavarian hilltop.',
    tags: ['Castle', 'Fairytale', 'Mountains'],
    latitude: 47.5576,
    longitude: 10.7498,
    priceLevel: 2,
    hours: 'Daily 9:00 AM – 6:00 PM (summer), 10:00 AM – 4:00 PM (winter)',
    phone: '+49 8362 93 98 80',
    website: 'https://www.neuschwanstein.de',
    reviewCount: 18400,
    address: 'Neuschwansteinstraße 20, 87645 Schwangau, Germany',
    bestTimeToVisit: 'Early September for warm weather and fall foliage beginning',
    duration: '2-3 hours',
    admissionFee: '€15 (adults), free for under 18',
    tips: [
      'Walk to Marienbrücke (Mary\'s Bridge) for THE postcard photo of the castle',
      'Timed entry is strict — arrive at the ticket center 30 minutes before your slot',
      'The uphill walk takes 30 minutes; horse carriage is available but often a long wait',
    ],
    accessibility: ['Steep uphill path to castle', 'Wheelchair users can request vehicle transport with advance notice'],
    nearbyPlaces: ['ev5', 'p11', 'p15'],
  },

  // ── Restaurants (~10) ─────────────────────────────────────
  {
    id: 'r1',
    name: 'Ichiran Ramen',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
    images: [
      'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
      'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=800',
      'https://images.unsplash.com/photo-1623341214825-9f4f963727da?w=800',
    ],
    type: 'restaurant',
    rating: 4.8,
    tagline: 'Shibuya, Tokyo',
    category: 'Japanese',
    description: 'Solo booth ramen with rich tonkotsu broth and custom spice.',
    tags: ['Ramen', 'Solo Dining', 'Iconic'],
    latitude: 35.6614,
    longitude: 139.6993,
    priceLevel: 1,
    hours: 'Daily 24 hours',
    phone: '+81 3 3463 3667',
    website: 'https://www.ichiran.com',
    reviewCount: 14200,
    address: '1-22-7 Jinnan, Shibuya-ku, Tokyo 150-0041, Japan',
    bestTimeToVisit: 'Late night for shortest wait times',
    duration: '30-45 minutes',
    tips: [
      'Use the vending machine to order and customize your spice level on the paper form',
      'Order the extra-firm noodle option (kata-men) for the authentic Hakata texture',
      'Hit the call button for kae-dama (extra noodles) before your broth gets cold',
    ],
    accessibility: ['Ground floor seating available', 'Narrow booth seating may not accommodate wheelchairs'],
    nearbyPlaces: ['r4', 'p20', 'ev7'],
  },
  {
    id: 'r2',
    name: 'Pizzeria da Michele',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
    type: 'restaurant',
    rating: 4.7,
    tagline: 'Naples, Italy',
    category: 'Italian',
    description: 'Since 1870 — only two pizzas on the menu, both perfect.',
    tags: ['Pizza', 'Historic', 'Authentic'],
    latitude: 40.8518,
    longitude: 14.2681,
    priceLevel: 1,
    hours: 'Mon–Sat 10:30 AM – 11:00 PM; closed Sunday',
    phone: '+39 081 553 9204',
    website: 'https://www.damichele.net',
    reviewCount: 18900,
    address: 'Via Cesare Sersale, 1, 80139 Napoli NA, Italy',
    bestTimeToVisit: 'Arrive by 11:30 AM or after 2:30 PM to avoid the worst queue',
    duration: '30-60 minutes',
    tips: [
      'There are only two options: Margherita and Marinara — get one of each to share',
      'The line moves faster than it looks; do not be discouraged',
      'Pay cash; cards are accepted now but cash is quicker',
    ],
    accessibility: ['Ground floor dining area', 'Narrow space between tables'],
    nearbyPlaces: ['p6', 'a3', 'p19'],
  },
  {
    id: 'r3',
    name: 'Cal Pep',
    image: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=800',
    type: 'restaurant',
    rating: 4.6,
    tagline: 'Barcelona, Spain',
    category: 'Spanish',
    description: 'Standing-room tapas bar with the freshest seafood in town.',
    tags: ['Tapas', 'Seafood', 'Bar'],
    latitude: 41.3836,
    longitude: 2.1821,
    priceLevel: 3,
    hours: 'Mon 7:30 PM – 11:30 PM, Tue–Sat 1:00 PM – 3:45 PM & 7:30 PM – 11:30 PM; closed Sunday',
    phone: '+34 933 107 961',
    website: 'https://www.calpep.com',
    reviewCount: 8700,
    address: 'Plaça de les Olles, 8, 08003 Barcelona, Spain',
    bestTimeToVisit: 'Arrive 15 minutes before opening for a bar seat',
    duration: '1-1.5 hours',
    tips: [
      'Sit at the bar and let Pep decide what you eat — the tasting selection is the way to go',
      'The fried artichokes and clams in white wine are non-negotiable',
      'Reservations only for the back dining room; the bar is first-come-first-served',
    ],
    accessibility: ['Ground floor entry', 'Bar stools may be challenging for some'],
    nearbyPlaces: ['a9', 'r7', 'ev6'],
  },
  {
    id: 'r4',
    name: 'Jiro Dreams of Sushi',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    type: 'restaurant',
    rating: 4.9,
    tagline: 'Ginza, Tokyo',
    category: 'Japanese',
    description: 'Legendary omakase from the master sushi chef.',
    tags: ['Sushi', 'Omakase', 'Michelin'],
    latitude: 35.6717,
    longitude: 139.7637,
    priceLevel: 4,
    hours: 'Mon–Sat, two seatings: 11:30 AM and 5:30 PM; closed Sunday & holidays',
    phone: '+81 3 3535 3600',
    website: 'https://www.sushi-jiro.jp',
    reviewCount: 5200,
    address: 'Tsukamoto Sogyo Building B1, 2-15 Ginza 4-chome, Chuo-ku, Tokyo 104-0061, Japan',
    bestTimeToVisit: 'Lunch seating is slightly easier to book',
    duration: '30-45 minutes',
    tips: [
      'Reservations must be made through a Japanese-speaking concierge — most luxury hotels can help',
      'The omakase is about 20 pieces served rapidly; do not expect a leisurely meal',
      'Eat each piece as soon as it is placed — temperature is part of the craft',
    ],
    accessibility: ['Basement level via stairs only', 'Only 10 seats at the counter'],
    nearbyPlaces: ['r1', 'p20', 'ev7'],
  },
  {
    id: 'r5',
    name: 'Café de Flore',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    type: 'restaurant',
    rating: 4.5,
    tagline: 'Saint-Germain, Paris',
    category: 'French',
    description: 'Historic literary café frequented by Sartre and de Beauvoir.',
    tags: ['Café', 'Historic', 'Literary'],
    latitude: 48.8540,
    longitude: 2.3325,
    priceLevel: 3,
    hours: 'Daily 7:30 AM – 1:30 AM',
    phone: '+33 1 45 48 55 26',
    website: 'https://www.cafedeflore.fr',
    reviewCount: 11400,
    address: '172 Boulevard Saint-Germain, 75006 Paris, France',
    bestTimeToVisit: 'Weekday morning for a terrace seat and Parisian people-watching',
    duration: '45-90 minutes',
    tips: [
      'Order the chocolat chaud (hot chocolate) — it is the signature and worth every centime',
      'Sit on the terrace if weather permits; the inside is charming but cramped',
      'The omelette and croque-monsieur are solid; skip the overpriced salads',
    ],
    accessibility: ['Ground floor terrace accessible', 'Interior has narrow aisles between tables'],
    nearbyPlaces: ['a2', 'ev3', 'r10'],
  },
  {
    id: 'r6',
    name: 'Dishoom',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    type: 'restaurant',
    rating: 4.7,
    tagline: 'London, England',
    category: 'Indian',
    description: 'Bombay-inspired café with legendary bacon naan rolls.',
    tags: ['Indian', 'Brunch', 'Trendy'],
    latitude: 51.5155,
    longitude: -0.1305,
    priceLevel: 2,
    hours: 'Mon–Fri 8:00 AM – 11:00 PM, Sat–Sun 9:00 AM – 11:00 PM',
    phone: '+44 20 7420 9320',
    website: 'https://www.dishoom.com',
    reviewCount: 22100,
    address: '12 Upper St Martin\'s Lane, London WC2H 9FB, United Kingdom',
    bestTimeToVisit: 'Breakfast for the famous bacon naan without the dinner queue',
    duration: '1-1.5 hours',
    tips: [
      'The bacon naan roll at breakfast is the single best thing you will eat in London',
      'Walk-ins only for breakfast; dinner queues can be 90 minutes on weekends',
      'Black daal is the signature; it is simmered for 24 hours and it shows',
    ],
    accessibility: ['Step-free entrance at King\'s Cross location', 'Accessible restrooms available'],
    nearbyPlaces: ['a2', 'ev3', 'r10'],
  },
  {
    id: 'r7',
    name: 'La Boqueria Market',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    type: 'restaurant',
    rating: 4.6,
    tagline: 'Las Ramblas, Barcelona',
    category: 'Market',
    description: 'Centuries-old market with fresh juices, jamón, and seafood.',
    tags: ['Market', 'Street Food', 'Fresh'],
    latitude: 41.3816,
    longitude: 2.1719,
    priceLevel: 2,
    hours: 'Mon–Sat 8:00 AM – 8:30 PM; closed Sunday',
    phone: '+34 933 182 584',
    website: 'https://www.boqueria.barcelona',
    reviewCount: 26400,
    address: 'La Rambla, 91, 08001 Barcelona, Spain',
    bestTimeToVisit: 'Weekday mornings before 10 AM when locals shop',
    duration: '1-2 hours',
    tips: [
      'Skip the stalls at the entrance — the best food is deeper inside the market',
      'Bar Pinotxo near the entrance is an exception; their chickpeas are legendary',
      'Fresh fruit cups are overpriced near the front; head to the back stalls',
    ],
    accessibility: ['Flat ground level throughout', 'Can be very crowded and difficult to navigate with mobility devices'],
    nearbyPlaces: ['r3', 'a9', 'ev6'],
  },
  {
    id: 'r8',
    name: 'Hawker Chan',
    image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=800',
    type: 'restaurant',
    rating: 4.5,
    tagline: 'Singapore',
    category: 'Asian',
    description: 'Cheapest Michelin-starred meal in the world — soya sauce chicken.',
    tags: ['Hawker', 'Michelin', 'Budget'],
    latitude: 1.2830,
    longitude: 103.8453,
    priceLevel: 1,
    hours: 'Daily 10:30 AM – 8:30 PM',
    phone: '+65 6227 2012',
    website: 'https://www.hawkerchan.com',
    reviewCount: 9600,
    address: '78 Smith Street, #02-126 Chinatown Complex, Singapore 058972',
    bestTimeToVisit: 'Before 11 AM to avoid the lunch rush queue',
    duration: '30-45 minutes',
    tips: [
      'Get the soya sauce chicken rice, not the noodle version — the rice soaks up the sauce',
      'The original Chinatown Complex stall is the one worth visiting, not the franchise outlets',
      'Queue can be 45 minutes at peak; consider a weekday mid-afternoon visit',
    ],
    accessibility: ['Hawker center is ground level', 'Seating is communal bench-style'],
    nearbyPlaces: ['a11', 'p3', 'e5'],
  },
  {
    id: 'r9',
    name: 'Cevichería',
    image: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=800',
    type: 'restaurant',
    rating: 4.7,
    tagline: 'Cartagena, Colombia',
    category: 'Latin American',
    description: 'Creative ceviche in a colonial courtyard with a giant jellyfish lamp.',
    tags: ['Ceviche', 'Seafood', 'Trendy'],
    latitude: 10.4236,
    longitude: -75.5474,
    priceLevel: 2,
    hours: 'Mon–Sat 12:00 PM – 3:30 PM & 6:30 PM – 10:30 PM; closed Sunday',
    phone: '+57 5 660 1492',
    website: 'https://www.cevicheriacartagena.com',
    reviewCount: 7300,
    address: 'Calle Stuart 7-14, Centro Histórico, Cartagena, Colombia',
    bestTimeToVisit: 'Lunch for the full menu and calmer atmosphere',
    duration: '1-1.5 hours',
    tips: [
      'The coconut ceviche is the signature — order it no matter what',
      'Make a reservation for dinner; walk-ins at lunch are usually fine',
      'Pair with a passion fruit margarita; it is the perfect complement',
    ],
    accessibility: ['Step-up entrance to colonial building', 'Interior courtyard is flat and spacious'],
    nearbyPlaces: ['p10', 'a6', 'a10'],
  },
  {
    id: 'r10',
    name: 'Noma',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    type: 'restaurant',
    rating: 4.9,
    tagline: 'Copenhagen, Denmark',
    category: 'Nordic',
    description: 'Pioneering New Nordic cuisine with foraged ingredients.',
    tags: ['Michelin', 'Nordic', 'Innovative'],
    latitude: 55.6832,
    longitude: 12.6104,
    priceLevel: 4,
    hours: 'Wed–Sun, two seatings: 12:00 PM and 5:00 PM; closed Mon–Tue',
    phone: '+45 32 96 32 97',
    website: 'https://www.noma.dk',
    reviewCount: 4800,
    address: 'Refshalevej 96, 1432 Copenhagen, Denmark',
    bestTimeToVisit: 'Seafood season (January–June) for the most acclaimed menu',
    duration: '2.5-3.5 hours',
    tips: [
      'Reservations open months ahead and sell out in minutes — set a calendar alert',
      'The wine pairing is extraordinary and worth the additional cost',
      'Expect 15-20 courses; come with an empty stomach and an open mind',
    ],
    accessibility: ['Ground level restaurant with accessible entrance', 'Staff accommodates dietary restrictions with advance notice'],
    nearbyPlaces: ['r6', 'p13', 'ev5'],
  },

  // ── Experiences (~12) ─────────────────────────────────────
  {
    id: 'e1',
    name: 'African Safari Drive',
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    images: [
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
      'https://images.unsplash.com/photo-1516426122078-c23e76b94d42?w=800',
      'https://images.unsplash.com/photo-1549366021-9f761d450615?w=800',
    ],
    type: 'experience',
    rating: 4.9,
    tagline: 'Masai Mara, Kenya',
    category: 'Adventure',
    description: 'Witness the Big Five in their natural habitat at golden hour.',
    tags: ['Safari', 'Wildlife', 'Africa'],
    latitude: -1.4061,
    longitude: 35.0137,
    priceLevel: 3,
    hours: 'Morning drives 6:00 AM – 10:00 AM, afternoon drives 3:30 PM – 6:30 PM',
    phone: '+254 20 271 6315',
    website: 'https://www.masaimara.com',
    reviewCount: 8900,
    address: 'Masai Mara National Reserve, Narok County, Kenya',
    bestTimeToVisit: '6:00 AM departure for best wildlife activity and golden light',
    duration: '4-6 hours',
    admissionFee: 'USD $80/day (park fee) plus safari vehicle hire',
    tips: [
      'The morning game drive sees more predator activity than the afternoon',
      'Bring a buff or scarf — the dust on dirt roads is intense',
      'A Maasai guide spots wildlife that visitors drive right past',
    ],
    accessibility: ['Modified safari vehicles with step assistance', 'Some lodges offer accessible rooms'],
    nearbyPlaces: ['p18', 'e10', 'p2'],
  },
  {
    id: 'e2',
    name: 'Scuba Diving Reef',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    type: 'experience',
    rating: 4.8,
    tagline: 'Great Barrier Reef, Australia',
    category: 'Water Sports',
    description: 'Dive among corals, turtles, and tropical fish.',
    tags: ['Diving', 'Marine Life', 'Coral'],
    latitude: -18.2871,
    longitude: 147.6992,
    priceLevel: 3,
    hours: 'Boat departures 8:00 AM and 12:00 PM daily',
    phone: '+61 7 4046 7333',
    website: 'https://www.greatbarrierreef.org',
    reviewCount: 11500,
    address: 'Cairns, QLD 4870, Australia',
    bestTimeToVisit: 'June–October for best visibility and calm seas',
    duration: '4-6 hours',
    admissionFee: 'AUD $250–$350 per person (full-day dive trip)',
    tips: [
      'Choose an outer reef trip over inner reef — the coral is healthier and more vibrant',
      'Introductory dives require no certification and go to 12 meters',
      'Apply reef-safe sunscreen only; chemical sunscreen damages the coral',
    ],
    accessibility: ['Some operators offer adaptive dive programs', 'Boat access may require climbing ladders'],
    nearbyPlaces: ['a11', 'p9', 'p14'],
  },
  {
    id: 'e3',
    name: 'Inca Trail Trek',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800',
    type: 'experience',
    rating: 4.9,
    tagline: 'Cusco, Peru',
    category: 'Trekking',
    description: 'Four-day trek through cloud forest to Machu Picchu.',
    tags: ['Trekking', 'Inca', 'Multi-Day'],
    latitude: -13.5170,
    longitude: -71.9785,
    priceLevel: 2,
    hours: 'Trek departs early morning Day 1 from km 82',
    phone: '+51 84 242 824',
    website: 'https://www.incatrailperu.com',
    reviewCount: 6800,
    address: 'Km 82, Cusco Region, Peru',
    bestTimeToVisit: 'May–September (dry season); trail closed every February for maintenance',
    duration: '4 days',
    admissionFee: 'USD $300–$600 (depends on operator, includes permits)',
    tips: [
      'Book 6 months in advance — only 500 permits per day including porters',
      'Spend 2 days acclimatizing in Cusco before starting; altitude hits hard on Day 2',
      'Hire a porter for your bag; you will thank yourself on Dead Woman\'s Pass at 4,215m',
    ],
    accessibility: ['Not suitable for mobility impairments', 'High altitude and steep terrain throughout'],
    nearbyPlaces: ['a6', 'p16', 'r9'],
  },
  {
    id: 'e4',
    name: 'Northern Lights Tour',
    image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    type: 'experience',
    rating: 4.7,
    tagline: 'Reykjavík, Iceland',
    category: 'Nature',
    description: 'Chase the aurora borealis across the Icelandic wilderness.',
    tags: ['Aurora', 'Night', 'Winter'],
    latitude: 64.1466,
    longitude: -21.9426,
    priceLevel: 2,
    hours: 'Tours depart 9:00 PM – 10:00 PM, return by 1:00 AM',
    phone: '+354 560 8800',
    website: 'https://www.re.is/northern-lights',
    reviewCount: 7400,
    address: 'BSÍ Bus Terminal, Vatnsmýrarvegur 10, 101 Reykjavík, Iceland',
    bestTimeToVisit: 'September–March; October and February have strongest activity',
    duration: '3-4 hours',
    admissionFee: 'ISK 8,900 (~USD $65) per person',
    tips: [
      'Small group minibus tours go further from the city for better displays',
      'Most tours offer a free rebooking if no lights appear',
      'Bring your own thermos of hot chocolate and hand warmers',
    ],
    accessibility: ['Minibus tours are more accessible than super jeep options', 'Standing outdoors in cold for extended periods required'],
    nearbyPlaces: ['p1', 'p13', 'e8'],
  },
  {
    id: 'e5',
    name: 'Thai Cooking Class',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800',
    type: 'experience',
    rating: 4.6,
    tagline: 'Chiang Mai, Thailand',
    category: 'Culinary',
    description: 'Market tour and hands-on cooking with a local chef.',
    tags: ['Cooking', 'Food', 'Cultural'],
    latitude: 18.7883,
    longitude: 98.9853,
    priceLevel: 1,
    hours: 'Morning class 8:30 AM – 1:00 PM, afternoon class 1:30 PM – 5:30 PM',
    phone: '+66 53 320 604',
    website: 'https://www.thaifarmcooking.com',
    reviewCount: 5100,
    address: 'Chiang Mai Old City, Chiang Mai 50200, Thailand',
    bestTimeToVisit: 'Morning class includes the market tour which is more vibrant',
    duration: '4-5 hours',
    admissionFee: 'THB 1,200 (~USD $35) including market tour and meal',
    tips: [
      'Choose a farm-based class over a city one — you pick your own herbs',
      'The morning class includes the Warorot Market visit which is fantastic',
      'Ask to learn khao soi (northern Thai curry noodle soup) if it is available',
    ],
    accessibility: ['Some farm classes require walking on uneven ground', 'City-based classes are more accessible'],
    nearbyPlaces: ['p3', 'a7', 'r8'],
  },
  {
    id: 'e6',
    name: 'Skydiving Interlaken',
    image: 'https://images.unsplash.com/photo-1474623809196-26c1d33457cc?w=800',
    type: 'experience',
    rating: 4.8,
    tagline: 'Interlaken, Switzerland',
    category: 'Extreme',
    description: 'Tandem skydive with views of Eiger, Mönch, and Jungfrau.',
    tags: ['Skydiving', 'Extreme', 'Alps'],
    latitude: 46.6863,
    longitude: 7.8632,
    priceLevel: 3,
    hours: 'Jumps at 9:00 AM, 11:00 AM, 1:00 PM, and 3:00 PM (weather permitting)',
    phone: '+41 33 821 0011',
    website: 'https://www.skydiveinterlaken.ch',
    reviewCount: 3400,
    address: 'Höheweg 101, 3800 Interlaken, Switzerland',
    bestTimeToVisit: 'Clear morning for the most spectacular alpine panorama',
    duration: '2-3 hours',
    admissionFee: 'CHF 430 (~USD $480) for tandem jump with video package',
    tips: [
      'Book the earliest slot — morning has the calmest air and clearest views',
      'The video package is worth it; your memory of the freefall will be a blur',
      'Wear layers you can remove; it is cold at altitude but warm on the ground',
    ],
    accessibility: ['Requires basic mobility to exit aircraft', 'Weight limit typically 100 kg'],
    nearbyPlaces: ['p11', 'a12', 'p8'],
  },
  {
    id: 'e7',
    name: 'Moroccan Desert Camp',
    image: 'https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800',
    type: 'experience',
    rating: 4.7,
    tagline: 'Merzouga, Morocco',
    category: 'Adventure',
    description: 'Camel ride to a luxury desert camp under the stars.',
    tags: ['Desert', 'Camping', 'Stars'],
    latitude: 31.0982,
    longitude: -4.0133,
    priceLevel: 2,
    hours: 'Camel departure: 4:00 PM, return ride: 8:00 AM next day',
    phone: '+212 535 577 130',
    website: 'https://www.saharadesertcamp.com',
    reviewCount: 4600,
    address: 'Erg Chebbi, Merzouga 52202, Morocco',
    bestTimeToVisit: 'October–April for cooler desert temperatures; new moon for stargazing',
    duration: '2 days (overnight)',
    admissionFee: 'MAD 1,500 (~USD $150) per person including meals',
    tips: [
      'Book a luxury camp with private tent and en-suite — the standard shared ones are rough',
      'The camel ride is 90 minutes; wear long pants to avoid chafing',
      'Bring a headlamp and download a star map app for the night sky',
    ],
    accessibility: ['Camel mounting requires leg mobility', 'Sandy terrain is difficult with mobility devices'],
    nearbyPlaces: ['p2', 'a1', 'p18'],
  },
  {
    id: 'e8',
    name: 'Glacier Hiking',
    image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800',
    type: 'experience',
    rating: 4.8,
    tagline: 'Sólheimajökull, Iceland',
    category: 'Adventure',
    description: 'Walk on ancient ice formations with crampons and ice axes.',
    tags: ['Glacier', 'Hiking', 'Ice'],
    latitude: 63.5308,
    longitude: -19.3660,
    priceLevel: 2,
    hours: 'Guided departures at 9:30 AM, 12:00 PM, and 2:30 PM',
    phone: '+354 587 9999',
    website: 'https://www.arcticadventures.is',
    reviewCount: 5800,
    address: 'Sólheimajökull Glacier, South Iceland',
    bestTimeToVisit: 'October–March for dramatic blue ice; summer for longer days',
    duration: '3-4 hours',
    admissionFee: 'ISK 12,990 (~USD $95) per person with gear',
    tips: [
      'All crampons, ice axes, and helmets are provided — bring warm waterproof layers',
      'Wear hiking boots with stiff soles; running shoes will not work with crampons',
      'The blue ice crevasses are incredible in winter; summer ice is grayer',
    ],
    accessibility: ['Requires ability to walk on uneven ice for 2+ hours', 'Not suitable for mobility impairments'],
    nearbyPlaces: ['p1', 'e4', 'p13'],
  },
  {
    id: 'e9',
    name: 'Tuscan Wine Tour',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800',
    type: 'experience',
    rating: 4.7,
    tagline: 'Chianti, Italy',
    category: 'Culinary',
    description: 'Visit three estates, taste Brunello, and lunch among vineyards.',
    tags: ['Wine', 'Vineyard', 'Tuscany'],
    latitude: 43.4789,
    longitude: 11.2566,
    priceLevel: 3,
    hours: 'Tours depart 9:30 AM, return by 5:00 PM',
    phone: '+39 055 234 6654',
    website: 'https://www.tuscanwinetours.com',
    reviewCount: 6200,
    address: 'Chianti Region, Province of Siena, Tuscany, Italy',
    bestTimeToVisit: 'September–October during harvest season for the most atmosphere',
    duration: '5-6 hours',
    admissionFee: '€130–€180 per person (includes tastings and lunch)',
    tips: [
      'Choose a small group tour (8 max) over a bus tour for better winery access',
      'Brunello di Montalcino estates are pricier but the wines are world-class',
      'Eat the bread with olive oil at every stop; Tuscan olive oil is as good as the wine',
    ],
    accessibility: ['Many wineries have gravel paths and stairs to cellars', 'Request accessible wineries when booking'],
    nearbyPlaces: ['p6', 'p19', 'a3'],
  },
  {
    id: 'e10',
    name: 'Bungee at Victoria Falls',
    image: 'https://images.unsplash.com/photo-1604537529428-15bcbeecfe4d?w=800',
    type: 'experience',
    rating: 4.6,
    tagline: 'Zambia/Zimbabwe',
    category: 'Extreme',
    description: '111-meter bungee jump over the Zambezi River.',
    tags: ['Bungee', 'Extreme', 'Waterfall'],
    latitude: -17.9243,
    longitude: 25.8572,
    priceLevel: 2,
    hours: 'Daily 9:00 AM – 5:00 PM',
    phone: '+263 77 243 9160',
    website: 'https://www.shearwatervictoriafalls.com',
    reviewCount: 3200,
    address: 'Victoria Falls Bridge, Victoria Falls, Zimbabwe',
    bestTimeToVisit: 'August–December when spray is low enough to see the gorge clearly',
    duration: '2-3 hours',
    admissionFee: 'USD $160 per jump',
    tips: [
      'Jump from the Zambia side for a slightly better view of the falls',
      'Go in the morning when the bridge is in sunlight for the best photos',
      'The bridge walk and gorge swing are available as lower-intensity alternatives',
    ],
    accessibility: ['Requires walking on a narrow bridge', 'Not suitable for mobility impairments'],
    nearbyPlaces: ['p18', 'e1', 'a8'],
  },
  {
    id: 'e11',
    name: 'Japanese Tea Ceremony',
    image: 'https://images.unsplash.com/photo-1545048702-79362596cdc9?w=800',
    type: 'experience',
    rating: 4.5,
    tagline: 'Kyoto, Japan',
    category: 'Cultural',
    description: 'Traditional matcha ceremony in a 200-year-old tea house.',
    tags: ['Tea', 'Traditional', 'Zen'],
    latitude: 35.0116,
    longitude: 135.7681,
    priceLevel: 2,
    hours: 'Sessions at 10:00 AM, 1:00 PM, and 3:00 PM',
    phone: '+81 75 431 6474',
    website: 'https://www.tea-ceremony-kyoto.com',
    reviewCount: 3900,
    address: 'Gion District, Higashiyama-ku, Kyoto 605-0073, Japan',
    bestTimeToVisit: 'Afternoon session for softer light in the tea room',
    duration: '2-3 hours',
    admissionFee: '¥5,000 (~USD $35) per person',
    tips: [
      'Wear socks without holes — you remove shoes and sit on tatami',
      'The host explains every gesture; follow along even if you do not understand every word',
      'Rotate the bowl twice before drinking as shown — it is a sign of respect',
    ],
    accessibility: ['Traditional tatami seating on the floor', 'Some venues offer chair seating with advance notice'],
    nearbyPlaces: ['p7', 'p20', 'r1'],
  },
  {
    id: 'e12',
    name: 'Helicopter Over Grand Canyon',
    image: 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800',
    type: 'experience',
    rating: 4.8,
    tagline: 'Arizona, USA',
    category: 'Adventure',
    description: 'Soar over the South Rim with champagne landing at the canyon floor.',
    tags: ['Helicopter', 'Canyon', 'Scenic'],
    latitude: 36.0544,
    longitude: -112.1401,
    priceLevel: 3,
    hours: 'Flights from 8:00 AM to 5:00 PM daily (sunrise tours by request)',
    phone: '+1 702 736 7243',
    website: 'https://www.papillon.com',
    reviewCount: 7600,
    address: 'Grand Canyon National Park, AZ 86023, USA',
    bestTimeToVisit: 'Early morning for calmest air and best canyon light',
    duration: '3-4 hours',
    admissionFee: 'USD $300–$500 per person (depends on route and landing)',
    tips: [
      'Request a front seat when booking — some operators charge extra but it is worth it',
      'The landing tours with champagne on the canyon floor are the premium experience',
      'Avoid midday flights; turbulence and haze increase significantly after noon',
    ],
    accessibility: ['Must be able to step into helicopter', 'Weight limits apply; check with operator'],
    nearbyPlaces: ['ev1', 'ev8', 'p8'],
  },

  // ── Events (~8) ───────────────────────────────────────────
  {
    id: 'ev1',
    name: 'Coachella Festival',
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    type: 'event',
    rating: 4.7,
    tagline: 'Indio, California',
    category: 'Music Festival',
    description: 'World-famous music and arts festival in the desert.',
    tags: ['Music', 'Festival', 'Desert'],
    latitude: 33.6803,
    longitude: -116.2375,
    priceLevel: 3,
    hours: 'Gates open 12:00 PM daily; music until 1:00 AM',
    phone: '+1 866 468 3399',
    website: 'https://www.coachella.com',
    reviewCount: 18700,
    address: 'Empire Polo Club, 81-800 Avenue 51, Indio, CA 92201, USA',
    bestTimeToVisit: 'Weekend 2 for slightly thinner crowds and same lineup',
    duration: '3 days',
    admissionFee: 'USD $549 (GA), $1,149 (VIP)',
    tips: [
      'Buy a locker — walking back to camp for forgotten items wastes hours',
      'Bring a portable phone charger; there is no reliable charging infrastructure',
      'Do Lab and Yuma tent have the best curated electronic music if the main stages are too packed',
    ],
    accessibility: ['ADA viewing platforms at all stages', 'Wheelchair-accessible camping and shuttles available'],
    nearbyPlaces: ['ev8', 'e12', 'ev2'],
  },
  {
    id: 'ev2',
    name: 'Art Basel Miami',
    image: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800',
    type: 'event',
    rating: 4.6,
    tagline: 'Miami Beach, Florida',
    category: 'Art Exhibition',
    description: 'Premier contemporary art fair with galleries from around the world.',
    tags: ['Art', 'Contemporary', 'Gallery'],
    latitude: 25.8003,
    longitude: -80.1300,
    priceLevel: 3,
    hours: 'Thu–Sat 12:00 PM – 8:00 PM, Sun 12:00 PM – 6:00 PM',
    phone: '+1 305 674 1292',
    website: 'https://www.artbasel.com/miami-beach',
    reviewCount: 9800,
    address: 'Miami Beach Convention Center, 1901 Convention Center Dr, Miami Beach, FL 33139, USA',
    bestTimeToVisit: 'Opening day for first pick; Saturday for the most satellite events',
    duration: '1-3 days',
    admissionFee: 'USD $65 (one day), $110 (multi-day)',
    tips: [
      'The satellite fairs (NADA, Untitled, Scope) are free or cheap and often more interesting',
      'Wynwood Walls has the best street art scene during Basel week',
      'Book hotels early; Miami Beach triples its prices during Art Basel week',
    ],
    accessibility: ['Convention center is fully wheelchair accessible', 'Satellite venues vary in accessibility'],
    nearbyPlaces: ['ev1', 'ev4', 'p10'],
  },
  {
    id: 'ev3',
    name: 'Cannes Film Festival',
    image: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800',
    type: 'event',
    rating: 4.8,
    tagline: 'Cannes, France',
    category: 'Film',
    description: 'The most prestigious film festival on the French Riviera.',
    tags: ['Film', 'Red Carpet', 'Glamour'],
    latitude: 43.5528,
    longitude: 7.0174,
    priceLevel: 3,
    hours: 'Screenings from 8:30 AM to midnight; red carpet events 6:00 PM – 8:00 PM',
    phone: '+33 4 92 99 84 00',
    website: 'https://www.festival-cannes.com',
    reviewCount: 7200,
    address: 'Palais des Festivals, 1 Bd de la Croisette, 06400 Cannes, France',
    bestTimeToVisit: 'May (two-week window); first weekend for opening night buzz',
    duration: '2-3 days',
    admissionFee: 'Free (public screenings at Cinéma de la Plage); accreditation for official screenings',
    tips: [
      'Cinéma de la Plage shows films on the beach for free every night during the festival',
      'Dress formally if you hope to get into any red-carpet-adjacent events',
      'The Marché du Film is where the industry deals happen; public access is limited',
    ],
    accessibility: ['Palais des Festivals is wheelchair accessible', 'Beach screenings may have limited accessible seating'],
    nearbyPlaces: ['a2', 'r5', 'p17'],
  },
  {
    id: 'ev4',
    name: 'Rio Carnival',
    image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800',
    type: 'event',
    rating: 4.9,
    tagline: 'Rio de Janeiro, Brazil',
    category: 'Cultural Festival',
    description: 'Samba parades, costumes, and the biggest party on Earth.',
    tags: ['Carnival', 'Samba', 'Party'],
    latitude: -22.9068,
    longitude: -43.1729,
    priceLevel: 2,
    hours: 'Street parties (blocos) all day; Sambadrome parades 9:00 PM – 5:00 AM',
    phone: '+55 21 2568 1014',
    website: 'https://www.rio-carnival.net',
    reviewCount: 14500,
    address: 'Sambadrome, R. Marquês de Sapucaí, Rio de Janeiro, RJ 20220-007, Brazil',
    bestTimeToVisit: 'February or March (dates shift); Sunday and Monday nights for top samba school parades',
    duration: '3-5 days',
    admissionFee: 'BRL 30–800 (Sambadrome seats vary by section); blocos are free',
    tips: [
      'The free street blocos are where the real party is — Cordão da Bola Preta is legendary',
      'Sambadrome Sector 9 offers the best view-to-price ratio',
      'Carry minimal cash, leave valuables at the hotel, and go in a group at night',
    ],
    accessibility: ['Sambadrome has wheelchair sections', 'Street blocos are chaotic and difficult with mobility devices'],
    nearbyPlaces: ['a8', 'p10', 'ev2'],
  },
  {
    id: 'ev5',
    name: 'Oktoberfest',
    image: 'https://images.unsplash.com/photo-1505489435671-80a165c60816?w=800',
    type: 'event',
    rating: 4.5,
    tagline: 'Munich, Germany',
    category: 'Cultural Festival',
    description: 'Traditional Bavarian beer festival with lederhosen and pretzels.',
    tags: ['Beer', 'Festival', 'German'],
    latitude: 48.1313,
    longitude: 11.5497,
    priceLevel: 2,
    hours: 'Mon–Fri 10:00 AM – 11:30 PM, Sat 9:00 AM – 11:30 PM, Sun 9:00 AM – 10:30 PM',
    phone: '+49 89 233 96 500',
    website: 'https://www.oktoberfest.de',
    reviewCount: 21300,
    address: 'Theresienwiese, 80339 Munich, Germany',
    bestTimeToVisit: 'Late September to early October; weekday mornings for guaranteed tent seating',
    duration: '1-2 days',
    admissionFee: 'Free entry; beer ~€14 per Maß (1 liter)',
    tips: [
      'Arrive before 10 AM on weekdays to guarantee a seat inside a tent',
      'The Augustiner tent is the locals\' favorite; Hofbräu is the tourist magnet',
      'Wear lederhosen or dirndl — it is not costume; locals actually wear them and you will feel out of place without',
    ],
    accessibility: ['Flat fairground terrain', 'Most tents have wheelchair-accessible areas near entrances'],
    nearbyPlaces: ['a12', 'p15', 'p11'],
  },
  {
    id: 'ev6',
    name: 'La Tomatina',
    image: 'https://images.unsplash.com/photo-1534531173927-aeb928d54385?w=800',
    type: 'event',
    rating: 4.4,
    tagline: 'Buñol, Spain',
    category: 'Cultural Festival',
    description: "The world's biggest tomato fight in a tiny Spanish town.",
    tags: ['Festival', 'Unique', 'Fun'],
    latitude: 39.4181,
    longitude: -0.7898,
    priceLevel: 1,
    hours: 'Fight: 11:00 AM – 12:00 PM (one hour only); festivities start 9:00 AM',
    phone: '+34 962 500 151',
    website: 'https://www.latomatina.info',
    reviewCount: 6100,
    address: 'Plaza del Pueblo, 46360 Buñol, Valencia, Spain',
    bestTimeToVisit: 'Last Wednesday of August (the only day it happens)',
    duration: '1 day',
    admissionFee: '€12 per person (ticket required since 2013)',
    tips: [
      'Wear clothes you plan to throw away; tomato stains permanently',
      'Wear goggles — the acidity stings your eyes badly',
      'Leave everything at your accommodation; there is nowhere safe to store belongings during the fight',
    ],
    accessibility: ['Extremely crowded narrow streets', 'Not recommended for mobility-impaired visitors'],
    nearbyPlaces: ['a9', 'r3', 'r7'],
  },
  {
    id: 'ev7',
    name: 'Cherry Blossom Season',
    image: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800',
    type: 'event',
    rating: 4.8,
    tagline: 'Tokyo, Japan',
    category: 'Seasonal',
    description: 'Hanami picnics under clouds of pink sakura blossoms.',
    tags: ['Sakura', 'Spring', 'Nature'],
    latitude: 35.7141,
    longitude: 139.7740,
    priceLevel: 2,
    hours: 'Parks: 5:00 AM – 11:00 PM; illuminated trees at night in select parks',
    phone: '+81 3 5321 3077',
    website: 'https://www.gotokyo.org/en/special/sakura',
    reviewCount: 16800,
    address: 'Ueno Park, Taito City, Tokyo 110-0007, Japan',
    bestTimeToVisit: 'Late March to early April (peak bloom shifts yearly; follow the forecast)',
    duration: '1-3 days',
    admissionFee: 'Free',
    tips: [
      'Shinjuku Gyoen closes early (4:30 PM) but is the most photogenic and least rowdy hanami spot',
      'Bring a blue tarp and arrive early to claim your picnic spot in Ueno Park',
      'Track the sakura forecast on japan-guide.com — peak bloom lasts only about one week',
    ],
    accessibility: ['Major parks have paved paths', 'Wheelchair accessible viewing areas in Shinjuku Gyoen'],
    nearbyPlaces: ['p20', 'r1', 'r4'],
  },
  {
    id: 'ev8',
    name: 'Burning Man',
    image: 'https://images.unsplash.com/photo-1504699894957-17572f33e2b2?w=800',
    type: 'event',
    rating: 4.6,
    tagline: 'Black Rock City, Nevada',
    category: 'Art Festival',
    description: 'Radical self-expression and massive art installations in the desert.',
    tags: ['Art', 'Community', 'Desert'],
    latitude: 40.7864,
    longitude: -119.2065,
    priceLevel: 3,
    hours: 'Open 24 hours for the full week; gates open Sunday before Labor Day',
    phone: '+1 415 863 5263',
    website: 'https://www.burningman.org',
    reviewCount: 11200,
    address: 'Black Rock Desert, Gerlach, NV 89412, USA',
    bestTimeToVisit: 'Late August through Labor Day Monday; the burn Saturday night is the climax',
    duration: '7 days',
    admissionFee: 'USD $575 (regular ticket) plus $140 vehicle pass',
    tips: [
      'Bring more water than you think — minimum 1.5 gallons per person per day',
      'A bike is essential; the playa is massive and walking everywhere is miserable',
      'Pack for 40°C days and near-freezing nights; the temperature swing is extreme',
    ],
    accessibility: ['Playa terrain is flat but dusty', 'Disabled access camps and art car accessibility available'],
    nearbyPlaces: ['ev1', 'e12', 'p8'],
  },
];
