import type { SuggestionCard } from '../types'

export const MOCK_SUGGESTIONS: SuggestionCard[] = [
  {
    id: 'sug-1',
    name: 'Eiffel Tower',
    category: 'sightseeing',
    imageUrl: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=300&h=220&fit=crop',
    duration: 2,
    price: 26,
    currency: 'EUR',
    rating: 4.7,
    location: '7th arrondissement, Paris',
    latitude: 48.8584,
    longitude: 2.2945,
    description: 'Iconic iron lattice tower on the Champ de Mars. Visit the summit for panoramic views of Paris. Best at sunset.',
    source: 'ai',
    relevanceScore: 0.95,
    reason: 'Top attraction in Paris',
  },
  {
    id: 'sug-2',
    name: 'Louvre Museum',
    category: 'museum',
    imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=300&h=260&fit=crop',
    duration: 3,
    price: 17,
    currency: 'EUR',
    rating: 4.8,
    location: '1st arrondissement, Paris',
    latitude: 48.8606,
    longitude: 2.3376,
    description: 'World\'s largest art museum. Home to the Mona Lisa, Venus de Milo, and 380,000+ works.',
    source: 'ai',
    relevanceScore: 0.93,
    reason: 'Must-see museum',
  },
  {
    id: 'sug-3',
    name: 'Le Bouillon Chartier',
    category: 'dining',
    imageUrl: 'https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=300&h=160&fit=crop',
    duration: 1.5,
    price: 15,
    currency: 'EUR',
    rating: 4.3,
    location: '9th arrondissement, Paris',
    latitude: 48.8745,
    longitude: 2.3444,
    description: 'Historic Parisian brasserie since 1896. Classic French dishes at unbeatable prices in a stunning Belle Époque dining hall.',
    source: 'ai',
    relevanceScore: 0.88,
    reason: 'Affordable local favorite',
  },
  {
    id: 'sug-4',
    name: 'Montmartre Walking Tour',
    category: 'tour',
    imageUrl: 'https://images.unsplash.com/photo-1478391679764-b2d8b3cd1e94?w=300&h=200&fit=crop',
    duration: 2.5,
    price: null,
    currency: 'EUR',
    rating: 4.6,
    location: '18th arrondissement, Paris',
    latitude: 48.8867,
    longitude: 2.3431,
    description: 'Explore the artistic hilltop village. See Sacré-Cœur, Place du Tertre artists, and hidden cobblestone streets.',
    source: 'ai',
    relevanceScore: 0.87,
    reason: 'Great for first-time visitors',
  },
  {
    id: 'sug-5',
    name: 'Sainte-Chapelle',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1509439581779-6298f75bf6e5?w=300&h=200&fit=crop',
    duration: 1,
    price: 11.5,
    currency: 'EUR',
    rating: 4.9,
    location: 'Île de la Cité, Paris',
    latitude: 48.8554,
    longitude: 2.3451,
    description: '13th-century Gothic chapel with the most stunning stained glass windows in Paris. 1,113 panels of biblical scenes.',
    source: 'ai',
    relevanceScore: 0.85,
    reason: 'Highest-rated cultural site',
  },
  {
    id: 'sug-6',
    name: 'Seine River Cruise',
    category: 'tour',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=300&h=170&fit=crop',
    duration: 1,
    price: 15,
    currency: 'EUR',
    rating: 4.4,
    location: 'Port de la Bourdonnais, Paris',
    latitude: 48.8600,
    longitude: 2.2885,
    description: 'Cruise past Notre-Dame, the Louvre, and the Eiffel Tower from the water.',
    source: 'ai',
    relevanceScore: 0.82,
  },
  {
    id: 'sug-7',
    name: 'Le Marais District',
    category: 'shopping',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=300&h=190&fit=crop',
    duration: 3,
    price: null,
    currency: 'EUR',
    rating: 4.5,
    location: '3rd & 4th arrondissement, Paris',
    latitude: 48.8566,
    longitude: 2.3622,
    description: 'Trendy boutiques, galleries, vintage shops, and the best falafel in Paris.',
    source: 'ai',
    relevanceScore: 0.80,
  },
  {
    id: 'sug-8',
    name: 'Moulin Rouge Show',
    category: 'nightlife',
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=300&h=230&fit=crop',
    duration: 2.5,
    price: 87,
    currency: 'EUR',
    rating: 4.2,
    location: 'Montmartre, Paris',
    latitude: 48.8841,
    longitude: 2.3322,
    description: 'Iconic cabaret show since 1889. Dazzling costumes, can-can dancers, and champagne.',
    source: 'ai',
    relevanceScore: 0.78,
  },
  {
    id: 'sug-9',
    name: 'Jardin du Luxembourg',
    category: 'outdoor',
    imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=300&h=180&fit=crop',
    duration: 1.5,
    price: null,
    currency: 'EUR',
    rating: 4.7,
    location: '6th arrondissement, Paris',
    latitude: 48.8462,
    longitude: 2.3372,
    description: 'Beautiful formal gardens. Relax by the Medici Fountain or rent a toy sailboat.',
    source: 'ai',
    relevanceScore: 0.76,
  },
  {
    id: 'sug-10',
    name: 'Musée d\'Orsay',
    category: 'museum',
    imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=300&h=200&fit=crop',
    duration: 2.5,
    price: 16,
    currency: 'EUR',
    rating: 4.8,
    location: '7th arrondissement, Paris',
    latitude: 48.8600,
    longitude: 2.3266,
    description: 'Impressionist and Post-Impressionist masterpieces in a stunning converted railway station.',
    source: 'ai',
    relevanceScore: 0.75,
  },
]
