import type { FlightOption, FlightDetailsType, PopularAirport } from '../types';

export const POPULAR_AIRPORTS: PopularAirport[] = [
  { code: "JFK", name: "John F. Kennedy International", city: "New York" },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles" },
  { code: "LHR", name: "Heathrow Airport", city: "London" },
  { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris" },
  { code: "NRT", name: "Narita International", city: "Tokyo" },
  { code: "FCO", name: "Leonardo da Vinci–Fiumicino", city: "Rome" },
  { code: "EWR", name: "Newark Liberty International", city: "Newark" },
  { code: "LGA", name: "LaGuardia Airport", city: "New York" },
  { code: "ORD", name: "O'Hare International", city: "Chicago" },
  { code: "SFO", name: "San Francisco International", city: "San Francisco" },
  { code: "MIA", name: "Miami International", city: "Miami" },
  { code: "DFW", name: "Dallas/Fort Worth International", city: "Dallas" },
  { code: "CIA", name: "Ciampino–G. B. Pastine", city: "Rome" },
];

export const FLIGHT_OPTIONS: FlightOption[] = [
  {
    id: "aa-101",
    airline: "American Airlines",
    airlineLogo: "AA",
    flightNumber: "AA-101",
    aircraft: "Boeing 777-300ER",
    departure: { time: "7:30 PM", airport: "JFK", terminal: "T8" },
    arrival: { time: "9:15 AM", airport: "FCO", terminal: "T3", nextDay: true },
    duration: "8h 45m",
    stops: 0,
    fareClass: "Economy",
    price: { base: 720, taxes: 130, total: 850 },
    baggage: { carryOn: true, checked: 1, checkedFee: 0 },
    seatPitch: "32\"",
    seatWidth: "17.5\"",
    amenities: { wifi: true, power: true, meals: true, entertainment: true },
    cancellation: { refundable: false, changeFee: 200, policy: "Non-refundable. Change fee applies." },
    onTime: 87,
    co2: 285,
    co2Avg: 310,
    milesEarned: 4280,
    alliance: "oneworld",
    badge: "Best Overall",
  },
  {
    id: "dl-420",
    airline: "Delta Air Lines",
    airlineLogo: "DL",
    flightNumber: "DL-420",
    aircraft: "Airbus A350-900",
    departure: { time: "5:45 PM", airport: "JFK", terminal: "T4" },
    arrival: { time: "7:05 AM", airport: "FCO", terminal: "T3", nextDay: true },
    duration: "8h 20m",
    stops: 0,
    fareClass: "Economy",
    price: { base: 780, taxes: 140, total: 920 },
    baggage: { carryOn: true, checked: 1, checkedFee: 0 },
    seatPitch: "33\"",
    seatWidth: "18\"",
    amenities: { wifi: true, power: true, meals: true, entertainment: true },
    cancellation: { refundable: true, changeFee: 0, policy: "Free cancellation up to 24 hours before departure." },
    onTime: 91,
    co2: 270,
    co2Avg: 310,
    milesEarned: 4280,
    alliance: "SkyTeam",
    badge: "Fastest",
  },
  {
    id: "ua-780",
    airline: "United Airlines",
    airlineLogo: "UA",
    flightNumber: "UA-780",
    aircraft: "Boeing 787-9 Dreamliner",
    departure: { time: "9:00 PM", airport: "EWR", terminal: "C" },
    arrival: { time: "11:10 AM", airport: "FCO", terminal: "T3", nextDay: true },
    duration: "9h 10m",
    stops: 0,
    fareClass: "Economy Plus",
    price: { base: 755, taxes: 140, total: 895 },
    baggage: { carryOn: true, checked: 1, checkedFee: 0 },
    seatPitch: "35\"",
    seatWidth: "18.5\"",
    amenities: { wifi: true, power: true, meals: true, entertainment: true },
    cancellation: { refundable: false, changeFee: 150, policy: "Change allowed with $150 fee per ticket." },
    onTime: 83,
    co2: 275,
    co2Avg: 310,
    milesEarned: 4280,
    alliance: "Star Alliance",
    badge: "Extra Legroom",
  },
  {
    id: "lh-233",
    airline: "Lufthansa",
    airlineLogo: "LH",
    flightNumber: "LH-233",
    aircraft: "Airbus A340-600",
    departure: { time: "4:15 PM", airport: "JFK", terminal: "T1" },
    arrival: { time: "9:30 AM", airport: "FCO", terminal: "T1", nextDay: true },
    duration: "12h 15m",
    stops: 1,
    layover: { airport: "FRA", duration: "2h 35m" },
    fareClass: "Economy",
    price: { base: 830, taxes: 145, total: 975 },
    baggage: { carryOn: true, checked: 1, checkedFee: 0 },
    seatPitch: "31\"",
    seatWidth: "17\"",
    amenities: { wifi: true, power: true, meals: true, entertainment: true },
    cancellation: { refundable: true, changeFee: 100, policy: "Refundable with fee. Free changes in 24 hours." },
    onTime: 78,
    co2: 340,
    co2Avg: 310,
    milesEarned: 5120,
    alliance: "Star Alliance",
    badge: null,
  },
  {
    id: "az-611",
    airline: "ITA Airways",
    airlineLogo: "AZ",
    flightNumber: "AZ-611",
    aircraft: "Airbus A321neo",
    departure: { time: "10:30 PM", airport: "JFK", terminal: "T1" },
    arrival: { time: "12:55 PM", airport: "FCO", terminal: "T1", nextDay: true },
    duration: "9h 25m",
    stops: 0,
    fareClass: "Economy",
    price: { base: 660, taxes: 125, total: 785 },
    baggage: { carryOn: true, checked: 1, checkedFee: 35 },
    seatPitch: "31\"",
    seatWidth: "17\"",
    amenities: { wifi: false, power: true, meals: true, entertainment: false },
    cancellation: { refundable: false, changeFee: 250, policy: "Non-refundable. High change fees apply." },
    onTime: 74,
    co2: 295,
    co2Avg: 310,
    milesEarned: 4280,
    alliance: "SkyTeam",
    badge: "Lowest Price",
  },
];

export const ALTERNATIVE_AIRPORTS = [
  { code: "EWR", name: "Newark (EWR)", savings: 45 },
  { code: "LGA", name: "LaGuardia (LGA)", savings: 20 },
  { code: "CIA", name: "Ciampino (CIA)", savings: 65 },
];

export const MOCK_FLIGHT_BOOKING_DETAILS: FlightDetailsType = {
  confirmationNumber: "TRVL2026-AA101",
  pnr: "XK7M2P",
  ticketNumbers: ["016-2468135790", "016-2468135791"],
  fareClass: "Economy (Y)",
  fareType: "Main Cabin",
  baggageAllowance: {
    carryOn: "1 carry-on bag + 1 personal item",
    checked: "1 checked bag up to 23kg (50lb)",
    fees: 0,
  },
  cancellationPolicy: "Non-refundable. Travel credit issued within 12 months.",
  changePolicy: "Change fee of $200 per ticket + fare difference.",
  refundPolicy: "Full refund within 24 hours of booking per DOT regulation.",
  checkInUrl: "https://www.aa.com/check-in",
  checkInOpens: "24 hours before departure",
};
