import type { CatalogItem } from '../types'

export const PACKING_CATALOG: CatalogItem[] = [
  // Clothing
  { name: 'T-shirts', category: 'clothing', tags: ['tops', 'shirts', 'tee'] },
  { name: 'Pants', category: 'clothing', tags: ['trousers', 'jeans', 'bottoms'] },
  { name: 'Shorts', category: 'clothing', tags: ['bottoms', 'summer'] },
  { name: 'Underwear', category: 'clothing', tags: ['undergarments', 'basics'] },
  { name: 'Socks', category: 'clothing', tags: ['basics', 'feet'] },
  { name: 'Jacket', category: 'clothing', tags: ['coat', 'outerwear', 'rain'] },
  { name: 'Rain jacket', category: 'clothing', tags: ['waterproof', 'outerwear', 'rain coat'] },
  { name: 'Sweater', category: 'clothing', tags: ['pullover', 'jumper', 'warm', 'hoodie'] },
  { name: 'Swimsuit', category: 'clothing', tags: ['swim', 'bathing suit', 'trunks', 'bikini', 'beach'] },
  { name: 'Pajamas', category: 'clothing', tags: ['sleepwear', 'pjs', 'nightwear'] },
  { name: 'Dress shoes', category: 'clothing', tags: ['formal', 'heels', 'loafers'] },
  { name: 'Walking shoes', category: 'clothing', tags: ['sneakers', 'trainers', 'comfortable'] },
  { name: 'Sandals', category: 'clothing', tags: ['flip flops', 'slides', 'beach'] },
  { name: 'Hiking boots', category: 'clothing', tags: ['trail', 'outdoor', 'trekking'] },
  { name: 'Belt', category: 'clothing', tags: ['accessories'] },
  { name: 'Dress', category: 'clothing', tags: ['formal', 'outfit', 'evening'] },
  { name: 'Warm layers', category: 'clothing', tags: ['thermal', 'base layer', 'fleece', 'cold'] },
  { name: 'Workout clothes', category: 'clothing', tags: ['gym', 'exercise', 'athletic', 'sports'] },
  { name: 'Scarf', category: 'clothing', tags: ['wrap', 'cold', 'winter'] },
  { name: 'Gloves', category: 'clothing', tags: ['cold', 'winter', 'mittens'] },
  { name: 'Hat', category: 'clothing', tags: ['cap', 'beanie', 'winter', 'warm'] },
  // Toiletries
  { name: 'Toothbrush', category: 'toiletries', tags: ['dental', 'teeth', 'oral'] },
  { name: 'Toothpaste', category: 'toiletries', tags: ['dental', 'teeth', 'oral'] },
  { name: 'Shampoo', category: 'toiletries', tags: ['hair', 'wash'] },
  { name: 'Conditioner', category: 'toiletries', tags: ['hair'] },
  { name: 'Body wash', category: 'toiletries', tags: ['soap', 'shower', 'gel'] },
  { name: 'Deodorant', category: 'toiletries', tags: ['antiperspirant'] },
  { name: 'Sunscreen', category: 'toiletries', tags: ['spf', 'sun protection', 'lotion', 'sunblock'] },
  { name: 'Moisturizer', category: 'toiletries', tags: ['lotion', 'cream', 'skin'] },
  { name: 'Razor', category: 'toiletries', tags: ['shaving', 'grooming'] },
  { name: 'Floss', category: 'toiletries', tags: ['dental', 'teeth'] },
  { name: 'Lip balm', category: 'toiletries', tags: ['chapstick', 'lips'] },
  { name: 'Hair brush', category: 'toiletries', tags: ['comb', 'hair'] },
  { name: 'Hair ties', category: 'toiletries', tags: ['elastic', 'ponytail', 'hair'] },
  { name: 'Contact lens supplies', category: 'toiletries', tags: ['contacts', 'solution', 'case', 'eyes'] },
  { name: 'Makeup', category: 'toiletries', tags: ['cosmetics', 'foundation', 'mascara'] },
  { name: 'Nail clippers', category: 'toiletries', tags: ['nails', 'grooming'] },
  { name: 'Tweezers', category: 'toiletries', tags: ['grooming'] },
  { name: 'Hand sanitizer', category: 'toiletries', tags: ['sanitizer', 'hygiene', 'clean'] },
  { name: 'Tissues', category: 'toiletries', tags: ['kleenex', 'wipes'] },
  { name: 'Bug spray', category: 'toiletries', tags: ['insect repellent', 'mosquito', 'deet'] },
  { name: 'Medications', category: 'toiletries', tags: ['medicine', 'prescription', 'pills', 'rx'] },
  { name: 'Pain reliever', category: 'toiletries', tags: ['ibuprofen', 'tylenol', 'aspirin', 'advil'] },
  { name: 'Band-aids', category: 'toiletries', tags: ['bandage', 'first aid', 'plaster'] },
  { name: 'Motion sickness pills', category: 'toiletries', tags: ['dramamine', 'nausea', 'travel'] },
  // Electronics
  { name: 'Phone charger', category: 'electronics', tags: ['cable', 'usb', 'charging', 'lightning'] },
  { name: 'Laptop', category: 'electronics', tags: ['computer', 'macbook'] },
  { name: 'Laptop charger', category: 'electronics', tags: ['power', 'cable', 'adapter'] },
  { name: 'Power adapter', category: 'electronics', tags: ['plug', 'converter', 'charger', 'outlet', 'international'] },
  { name: 'Portable battery', category: 'electronics', tags: ['power bank', 'charger', 'backup'] },
  { name: 'Headphones', category: 'electronics', tags: ['earbuds', 'airpods', 'earphones', 'audio'] },
  { name: 'Camera', category: 'electronics', tags: ['photo', 'photography', 'dslr', 'gopro'] },
  { name: 'Camera charger', category: 'electronics', tags: ['battery', 'photo'] },
  { name: 'Memory card', category: 'electronics', tags: ['sd card', 'storage', 'camera'] },
  { name: 'E-reader', category: 'electronics', tags: ['kindle', 'book', 'reading'] },
  { name: 'Tablet', category: 'electronics', tags: ['ipad', 'device'] },
  { name: 'Portable speaker', category: 'electronics', tags: ['bluetooth', 'music', 'audio'] },
  { name: 'Travel router', category: 'electronics', tags: ['wifi', 'internet', 'hotspot'] },
  { name: 'Extension cord', category: 'electronics', tags: ['power strip', 'outlet', 'plug'] },
  { name: 'USB cable', category: 'electronics', tags: ['charging', 'data', 'type-c'] },
  // Documents
  { name: 'Passport', category: 'documents', tags: ['id', 'identification', 'travel document'] },
  { name: 'Visa', category: 'documents', tags: ['travel permit', 'entry'] },
  { name: "Driver's license", category: 'documents', tags: ['id', 'identification', 'driving'] },
  { name: 'Travel insurance', category: 'documents', tags: ['insurance', 'policy', 'coverage'] },
  { name: 'Boarding pass', category: 'documents', tags: ['flight', 'ticket', 'airline'] },
  { name: 'Hotel confirmation', category: 'documents', tags: ['booking', 'reservation', 'accommodation'] },
  { name: 'Car rental confirmation', category: 'documents', tags: ['booking', 'reservation', 'vehicle'] },
  { name: 'Copies of documents', category: 'documents', tags: ['backup', 'photocopy', 'scan'] },
  { name: 'Emergency contacts', category: 'documents', tags: ['phone numbers', 'info'] },
  { name: 'Vaccination records', category: 'documents', tags: ['health', 'immunization', 'covid'] },
  { name: 'Credit cards', category: 'documents', tags: ['payment', 'bank', 'money'] },
  { name: 'Cash', category: 'documents', tags: ['money', 'currency', 'bills'] },
  { name: 'Student ID', category: 'documents', tags: ['identification', 'discount'] },
  // Accessories
  { name: 'Sunglasses', category: 'accessories', tags: ['shades', 'sun', 'eyes', 'uv'] },
  { name: 'Sun hat', category: 'accessories', tags: ['cap', 'sun protection', 'beach'] },
  { name: 'Umbrella', category: 'accessories', tags: ['rain', 'weather'] },
  { name: 'Day bag', category: 'accessories', tags: ['backpack', 'daypack', 'small bag'] },
  { name: 'Packing cubes', category: 'accessories', tags: ['organizer', 'luggage'] },
  { name: 'Neck pillow', category: 'accessories', tags: ['travel pillow', 'flight', 'sleep'] },
  { name: 'Eye mask', category: 'accessories', tags: ['sleep mask', 'flight', 'rest'] },
  { name: 'Earplugs', category: 'accessories', tags: ['noise', 'sleep', 'flight'] },
  { name: 'Water bottle', category: 'accessories', tags: ['hydration', 'drink', 'reusable'] },
  { name: 'Travel lock', category: 'accessories', tags: ['padlock', 'security', 'luggage'] },
  { name: 'Luggage tags', category: 'accessories', tags: ['bag', 'identification'] },
  { name: 'Laundry bag', category: 'accessories', tags: ['dirty clothes', 'wash'] },
  { name: 'Tote bag', category: 'accessories', tags: ['shopping', 'foldable', 'beach'] },
  { name: 'Travel wallet', category: 'accessories', tags: ['passport holder', 'organizer'] },
  { name: 'Jewelry', category: 'accessories', tags: ['watch', 'ring', 'necklace'] },
  { name: 'Book', category: 'accessories', tags: ['reading', 'novel', 'paperback'] },
  { name: 'Journal', category: 'accessories', tags: ['notebook', 'diary', 'writing'] },
  { name: 'Pen', category: 'accessories', tags: ['writing', 'customs form'] },
  { name: 'Playing cards', category: 'accessories', tags: ['games', 'entertainment', 'cards'] },
  { name: 'Binoculars', category: 'accessories', tags: ['bird watching', 'sightseeing'] },
  // Essentials
  { name: 'Wallet', category: 'essentials', tags: ['purse', 'money', 'cards'] },
  { name: 'Phone', category: 'essentials', tags: ['mobile', 'cell', 'smartphone'] },
  { name: 'Keys', category: 'essentials', tags: ['house key', 'car key'] },
  { name: 'Snacks', category: 'essentials', tags: ['food', 'granola', 'bars', 'trail mix'] },
  { name: 'Gum', category: 'essentials', tags: ['mint', 'breath', 'chewing'] },
  { name: 'Reusable shopping bag', category: 'essentials', tags: ['tote', 'grocery', 'eco'] },
  { name: 'Ziplock bags', category: 'essentials', tags: ['plastic bags', 'storage', 'liquids'] },
  { name: 'Tissues pack', category: 'essentials', tags: ['pocket tissues', 'kleenex'] },
  { name: 'Hand wipes', category: 'essentials', tags: ['wet wipes', 'cleaning'] },
  { name: 'Trash bags', category: 'essentials', tags: ['garbage', 'waste'] },
]
